import { C1DetailedChapter } from './c1Notes'

export const A12_DETAILED_CHAPTERS: C1DetailedChapter[] = [
  {
    id: 'cost-volume-profit-analysis',
    number: 1,
    title: '本量利分析',
    titleEn: 'Cost-Volume-Profit Analysis',
    objective: {
      zh: '理解成本、銷量及利潤之間的關係，計算損益平衡點、目標利潤銷量、安全邊際，並在單一產品及多產品情境下支援短期決策。',
      en: 'Understand the relationship among cost, volume and profit, calculate breakeven point, target-profit sales, margin of safety, and support short-term decisions in single-product and multiple-product situations.',
    },
    sections: [
      {
        title: '本量利分析的基礎',
        titleEn: 'Basics of CVP Analysis',
        points: [
          { zh: '本量利分析研究銷售價格、銷量、變動成本、固定成本及利潤之間的關係，常用於定價、產量規劃及短期決策。', en: 'Cost-volume-profit analysis studies the relationship among selling price, sales volume, variable costs, fixed costs and profit, and is used for pricing, output planning and short-term decisions.' },
          { zh: '貢獻是銷售收入減變動成本後的金額，用來彌補固定成本及提供利潤。單位貢獻 = 單位售價 - 單位變動成本。', en: 'Contribution is sales revenue less variable costs. It covers fixed costs and provides profit. Contribution per unit = selling price per unit - variable cost per unit.' },
          { zh: '貢獻式損益表先列銷售收入、變動成本及貢獻，再扣除固定成本得出利潤，能清楚顯示銷量變化對利潤的影響。', en: 'A contribution income statement shows sales revenue, variable costs and contribution before deducting fixed costs to arrive at profit, making the profit effect of volume changes clear.' },
          { zh: 'CVP 通常假設售價、單位變動成本及固定成本在相關範圍內保持不變，且產量等於銷量。作答時應留意題目是否改變這些假設。', en: 'CVP usually assumes selling price, variable cost per unit and fixed costs remain constant within the relevant range, and production equals sales. Check whether the question changes these assumptions.' },
        ],
      },
      {
        title: '損益平衡點',
        titleEn: 'Breakeven Point',
        points: [
          { zh: '損益平衡點是總收入等於總成本、利潤為零的銷量或銷售額。企業在此點以上才開始產生利潤。', en: 'Breakeven point is the sales volume or sales value at which total revenue equals total cost and profit is zero. Profit begins above this point.' },
          { zh: '方程式法：銷售收入 - 變動成本 - 固定成本 = 利潤。損益平衡時利潤為零，因此可解出所需銷量。', en: 'Equation method: sales revenue - variable costs - fixed costs = profit. At breakeven, profit is zero, so the required sales volume can be solved.' },
          { zh: '貢獻法：損益平衡銷量 = 固定成本 / 單位貢獻；損益平衡銷售額 = 固定成本 / 貢獻率。', en: 'Contribution margin method: breakeven units = fixed costs / contribution per unit; breakeven sales value = fixed costs / contribution margin ratio.' },
          { zh: '貢獻率 = 貢獻 / 銷售收入，亦可用單位貢獻 / 單位售價計算。它表示每一元銷售可產生多少貢獻。', en: 'Contribution margin ratio = contribution / sales revenue, or contribution per unit / selling price per unit. It shows contribution generated by each dollar of sales.' },
        ],
      },
      {
        title: '目標利潤與安全邊際',
        titleEn: 'Target Profit and Margin of Safety',
        points: [
          { zh: '目標利潤銷量 = (固定成本 + 目標利潤) / 單位貢獻；目標利潤銷售額 = (固定成本 + 目標利潤) / 貢獻率。', en: 'Target-profit units = (fixed costs + target profit) / contribution per unit; target-profit sales value = (fixed costs + target profit) / contribution margin ratio.' },
          { zh: '若題目涉及稅後目標利潤，應先把稅後利潤轉為稅前利潤，再代入公式。稅前利潤 = 稅後利潤 / (1 - 稅率)。', en: 'If an after-tax target profit is given, convert it to before-tax profit before using the formula. Profit before tax = profit after tax / (1 - tax rate).' },
          { zh: '安全邊際 = 實際或預計銷售 - 損益平衡銷售。安全邊際越大，企業承受銷售下降而不致虧損的能力越強。', en: 'Margin of safety = actual or budgeted sales - breakeven sales. A larger margin of safety means the business can tolerate a larger fall in sales before making a loss.' },
          { zh: '安全邊際率 = 安全邊際 / 實際或預計銷售 x 100%。它用百分比表示銷售可下跌的空間，便於不同規模企業比較。', en: 'Margin of safety ratio = margin of safety / actual or budgeted sales x 100%. It expresses the possible fall in sales as a percentage, allowing comparison across different business sizes.' },
        ],
      },
      {
        title: '多產品與加權平均法',
        titleEn: 'Multiple Products and Weighted Average Method',
        points: [
          { zh: '多產品 CVP 分析需要假設銷售組合保持不變。若銷售組合改變，加權平均貢獻和損益平衡點也會改變。', en: 'Multiple-product CVP analysis assumes the sales mix remains constant. If the sales mix changes, weighted average contribution and breakeven point change as well.' },
          { zh: '加權平均單位貢獻 = 各產品單位貢獻按銷售組合加權後的平均。損益平衡組合數 = 固定成本 / 加權平均單位貢獻。', en: 'Weighted average contribution per unit is the average of each product’s contribution per unit weighted by the sales mix. Breakeven sales mix units = fixed costs / weighted average contribution per unit.' },
          { zh: '若以銷售額組合作分析，可計算加權平均貢獻率，再用固定成本除以加權平均貢獻率求出損益平衡銷售額。', en: 'If analysis is based on sales-value mix, calculate the weighted average contribution margin ratio, then divide fixed costs by it to find breakeven sales value.' },
          { zh: '多產品題必須清楚列示組合比例及每種產品的銷量或銷售額，否則答案難以追蹤。', en: 'For multiple-product questions, show the sales mix and each product’s units or sales value clearly, otherwise the answer is difficult to follow.' },
        ],
      },
      {
        title: '限制因素下的決策',
        titleEn: 'Decisions Under Limiting Factors',
        points: [
          { zh: '限制因素是限制企業生產或銷售能力的稀缺資源，例如機器小時、直接人工小時、原材料或市場需求。', en: 'A limiting factor is a scarce resource that restricts production or sales capacity, such as machine hours, direct labour hours, materials or market demand.' },
          { zh: '有單一限制因素時，應按每單位限制因素的貢獻排序，而不是按單位貢獻或售價排序。', en: 'With one limiting factor, rank products by contribution per unit of the limiting factor, not by contribution per unit or selling price.' },
          { zh: '每單位限制因素貢獻 = 單位貢獻 / 每單位產品所需限制因素。優先生產此比率較高的產品，直至資源用盡或需求滿足。', en: 'Contribution per unit of limiting factor = contribution per unit / limiting factor required per unit. Prioritise products with the higher ratio until the resource is exhausted or demand is met.' },
          { zh: '若題目有最低合約要求、最高市場需求或多個限制因素，應先滿足必要條件，再分析剩餘資源的最佳用途。', en: 'If there are minimum contract requirements, maximum market demand or multiple limiting factors, satisfy compulsory conditions first and then analyse the best use of remaining resources.' },
        ],
      },
    ],
    terms: [
      { term: '本量利分析', termEn: 'Cost-volume-profit analysis', definition: '分析成本、銷量及利潤之間關係的管理會計工具。', definitionEn: 'A management accounting tool for analysing the relationship among cost, volume and profit.' },
      { term: '損益平衡點', termEn: 'Breakeven point', definition: '總收入等於總成本、利潤為零的銷量或銷售額。', definitionEn: 'The sales volume or sales value at which total revenue equals total cost and profit is zero.' },
      { term: '貢獻', termEn: 'Contribution margin', definition: '銷售收入減變動成本後用以彌補固定成本及提供利潤的金額。', definitionEn: 'Sales revenue less variable costs, used to cover fixed costs and provide profit.' },
      { term: '單位貢獻', termEn: 'Contribution per unit', definition: '每銷售一單位產品所產生的貢獻。', definitionEn: 'The contribution generated from selling one unit of product.' },
      { term: '貢獻率', termEn: 'Contribution margin ratio', definition: '貢獻佔銷售收入的比例。', definitionEn: 'Contribution as a proportion of sales revenue.' },
      { term: '貢獻式損益表', termEn: 'Contribution income statement', definition: '先扣除變動成本得出貢獻，再扣除固定成本得出利潤的損益表。', definitionEn: 'An income statement that deducts variable costs to show contribution before deducting fixed costs to calculate profit.' },
      { term: '目標利潤分析', termEn: 'Target profit analysis', definition: '計算達到指定利潤所需銷量或銷售額的分析。', definitionEn: 'Analysis calculating the sales volume or value required to achieve a specified profit.' },
      { term: '安全邊際', termEn: 'Margin of safety', definition: '實際或預計銷售超過損益平衡銷售的部分。', definitionEn: 'The excess of actual or budgeted sales over breakeven sales.' },
      { term: '安全邊際率', termEn: 'Margin of safety ratio', definition: '安全邊際佔實際或預計銷售的百分比。', definitionEn: 'Margin of safety expressed as a percentage of actual or budgeted sales.' },
      { term: '銷售組合', termEn: 'Sales mix', definition: '不同產品銷量或銷售額之間的比例。', definitionEn: 'The proportion of units or sales value represented by different products.' },
      { term: '加權平均法', termEn: 'Weighted average method', definition: '按銷售組合計算平均貢獻或貢獻率的方法。', definitionEn: 'A method that calculates average contribution or contribution margin ratio using the sales mix.' },
      { term: '限制因素', termEn: 'Limiting factor', definition: '限制企業生產或銷售能力的稀缺資源。', definitionEn: 'A scarce resource that restricts a business’s production or sales capacity.' },
    ],
    examTips: [
      { zh: 'CVP 題先寫單位貢獻，再選公式。很多錯誤來自直接用售價或銷售額代替貢獻。', en: 'In CVP questions, calculate contribution per unit first, then choose the formula. Many errors come from using selling price or sales value instead of contribution.' },
      { zh: '多產品題必須檢查銷售組合是否固定；若有組合比例，先算加權平均貢獻，再推算各產品銷量。', en: 'For multiple-product questions, check whether the sales mix is fixed. If a mix ratio is given, calculate weighted average contribution first, then derive each product’s sales volume.' },
      { zh: '有限資源題應按每單位限制因素貢獻排序，不應只選單位貢獻最高的產品。', en: 'For scarce-resource questions, rank by contribution per unit of limiting factor, not simply by the highest contribution per unit.' },
    ],
    questions: [
      { question: '為何損益平衡點不是以銷售收入直接除以固定成本計算？', questionEn: 'Why is breakeven point not calculated by dividing sales revenue directly by fixed costs?', answer: '因為銷售收入要先扣除變動成本，只有貢獻可用來彌補固定成本。損益平衡點應以固定成本除以單位貢獻或貢獻率計算。', answerEn: 'Sales revenue must first cover variable costs; only contribution is available to cover fixed costs. Breakeven should be calculated using fixed costs divided by contribution per unit or contribution margin ratio.' },
      { question: '安全邊際有何管理意義？', questionEn: 'What is the management meaning of margin of safety?', answer: '它顯示銷售可下降多少而不會產生虧損，安全邊際越高，營運風險通常越低。', answerEn: 'It shows how much sales can fall before a loss is made. A higher margin of safety usually means lower operating risk.' },
      { question: '有機器小時限制時，為何要看每機器小時貢獻？', questionEn: 'Why should contribution per machine hour be considered when machine hours are limited?', answer: '因為機器小時是稀缺資源，企業應優先把每一機器小時帶來較高貢獻的產品排在前面。', answerEn: 'Machine hours are the scarce resource, so the business should prioritise products that generate higher contribution for each machine hour used.' },
    ],
  },
  {
    id: 'cost-accounting-for-decision-making',
    number: 2,
    title: '決策成本會計',
    titleEn: 'Cost Accounting for Decision-making',
    objective: {
      zh: '分辨相關及不相關成本，運用差額分析處理特殊訂單、自製或外購、出售或進一步加工、更換設備及部門保留等短期決策。',
      en: 'Distinguish relevant and irrelevant costs, and use differential analysis for special orders, make-or-buy, sell-or-process-further, equipment replacement and segment-retention decisions.',
    },
    sections: [
      {
        title: '相關成本與不相關成本',
        titleEn: 'Relevant and Irrelevant Costs',
        points: [
          { zh: '相關成本是未來會發生且會因不同方案而改變的成本或收益。決策時只比較相關項目，避免被歷史成本或共同成本干擾。', en: 'Relevant costs are future costs or revenues that differ between alternatives. Decisions should compare only relevant items and avoid being distracted by historical or common costs.' },
          { zh: '不相關成本不會因方案選擇而改變，或已經發生不能改變，因此不應影響短期決策。', en: 'Irrelevant costs do not change between alternatives or have already been incurred and cannot be changed, so they should not affect short-term decisions.' },
          { zh: '差額分析的核心是「選擇某方案會額外增加或減少甚麼？」答案應列示增量收入、可避免成本、機會成本及其他相關影響。', en: 'The core of differential analysis is asking “what additional increases or decreases result from choosing this option?” Answers should show incremental revenue, avoidable costs, opportunity costs and other relevant effects.' },
        ],
      },
      {
        title: '常見成本概念',
        titleEn: 'Common Decision Cost Concepts',
        points: [
          { zh: '沉沒成本是已經發生且不能因未來決策改變的成本，例如已購設備的原始成本。沉沒成本不相關。', en: 'A sunk cost has already been incurred and cannot be changed by future decisions, such as the original cost of equipment already purchased. Sunk costs are irrelevant.' },
          { zh: '承諾成本是企業已承諾或必須承擔的未來成本；若無論選擇哪個方案都會發生，通常不相關。', en: 'Committed costs are future costs the business has already committed to or must incur. If they occur under all alternatives, they are usually irrelevant.' },
          { zh: '不可避免成本是不論採取哪個方案都不能避免的成本；可避免成本則會因放棄某方案而節省，通常是相關成本。', en: 'Unavoidable costs cannot be avoided under any alternative; avoidable costs can be saved by dropping an option and are usually relevant.' },
          { zh: '機會成本是選擇某方案而放棄下一最佳替代方案的利益，雖然未必有會計分錄，但在決策中屬相關成本。', en: 'Opportunity cost is the benefit forgone by choosing one option instead of the next best alternative. It may not be recorded in accounts but is relevant in decisions.' },
          { zh: '增量成本及增量收入是因選擇某方案而額外產生的成本及收入，是短期決策的主要比較基礎。', en: 'Incremental costs and revenues are additional costs and revenues caused by choosing an option, forming the main basis for short-term decision comparisons.' },
        ],
      },
      {
        title: '接受或拒絕特殊訂單',
        titleEn: 'Accept or Reject a Special Order',
        points: [
          { zh: '特殊訂單通常以低於正常售價提出。若企業有閒置產能，決策重點是訂單收入是否足以彌補相關增量成本。', en: 'A special order is often offered at a price below the normal selling price. If there is spare capacity, the key is whether order revenue covers relevant incremental costs.' },
          { zh: '若接受訂單不影響正常銷售，原有固定成本通常不相關，除非接受訂單會產生額外固定成本。', en: 'If accepting the order does not affect normal sales, existing fixed costs are usually irrelevant unless extra fixed costs are incurred.' },
          { zh: '若沒有閒置產能，接受特殊訂單可能會犧牲正常銷售，放棄正常訂單的貢獻就是機會成本，必須納入比較。', en: 'If there is no spare capacity, accepting a special order may sacrifice normal sales. The contribution forgone from normal orders is an opportunity cost and must be included.' },
        ],
      },
      {
        title: '自製、外購或租用',
        titleEn: 'Make, Buy, Hire or Use Internally',
        points: [
          { zh: '自製或外購決策比較外購價格與自製的相關成本。自製成本中只有可避免或會改變的成本相關，不可避免固定成本不應列入。', en: 'A make-or-buy decision compares purchase price with relevant make costs. Only avoidable or changing costs of making are relevant; unavoidable fixed costs should be excluded.' },
          { zh: '若外購可釋放產能作其他用途，該替代用途產生的貢獻或節省成本是外購方案的相關利益。', en: 'If buying frees capacity for another use, contribution earned or cost saved from that alternative use is a relevant benefit of buying.' },
          { zh: '租用或購買設備時，應比較未來現金流、維修成本、殘值、產能影響及任何機會成本；已擁有設備的帳面值通常是沉沒成本。', en: 'When hiring or buying equipment, compare future cash flows, maintenance costs, residual value, capacity effects and opportunity costs; the carrying amount of existing equipment is usually a sunk cost.' },
        ],
      },
      {
        title: '出售或進一步加工',
        titleEn: 'Sell Now or Process Further',
        points: [
          { zh: '出售或進一步加工決策只比較分離點之後的增量收入和增量成本。分離點前共同成本已經發生或無法因方案改變，通常不相關。', en: 'Sell-or-process-further decisions compare only incremental revenue and incremental cost after the split-off point. Joint costs before split-off have already been incurred or do not change and are usually irrelevant.' },
          { zh: '若進一步加工帶來的額外收入大於額外加工成本，財務上應進一步加工；反之應即時出售。', en: 'If additional revenue from further processing exceeds additional processing cost, the product should be processed further financially; otherwise it should be sold now.' },
          { zh: '若進一步加工佔用稀缺資源，亦要考慮該資源可用於其他產品時放棄的貢獻。', en: 'If further processing uses a scarce resource, the contribution forgone from using that resource for another product must also be considered.' },
        ],
      },
      {
        title: '更換設備與部門取捨',
        titleEn: 'Replace Equipment and Retain or Eliminate a Segment',
        points: [
          { zh: '更換設備決策應比較保留舊設備與購買新設備的未來相關現金流，包括營運成本、維修成本、新設備成本、舊設備出售收入及殘值。', en: 'Equipment replacement decisions compare future relevant cash flows of keeping old equipment and buying new equipment, including operating costs, maintenance, new equipment cost, proceeds from selling old equipment and residual values.' },
          { zh: '舊設備的原始成本及帳面值通常是沉沒成本，不應影響是否更換；但舊設備現在可出售的收入是相關項目。', en: 'The original cost and carrying amount of old equipment are usually sunk costs and should not affect replacement decisions; however, current disposal proceeds are relevant.' },
          { zh: '取消虧損部門時，應判斷哪些收入和成本會消失。若部門貢獻大於可避免固定成本，取消部門可能令整體利潤下降。', en: 'When eliminating an unprofitable segment, identify which revenue and costs will disappear. If the segment’s contribution exceeds avoidable fixed costs, eliminating it may reduce overall profit.' },
          { zh: '共同固定成本若取消部門後仍會存在，屬不可避免成本，不應歸咎於該部門作取消決策。', en: 'Common fixed costs that remain after a segment is eliminated are unavoidable and should not be charged to the segment for elimination decisions.' },
        ],
      },
    ],
    terms: [
      { term: '相關成本', termEn: 'Relevant cost', definition: '未來會發生且會因不同方案而改變的成本。', definitionEn: 'A future cost that differs between alternatives.' },
      { term: '不相關成本', termEn: 'Irrelevant cost', definition: '不會因方案選擇而改變，或已經發生不可改變的成本。', definitionEn: 'A cost that does not differ between alternatives or has already been incurred and cannot be changed.' },
      { term: '機會成本', termEn: 'Opportunity cost', definition: '選擇某方案而放棄下一最佳替代方案的利益。', definitionEn: 'The benefit forgone by choosing one option instead of the next best alternative.' },
      { term: '增量成本', termEn: 'Incremental cost', definition: '因選擇某方案而額外產生的成本。', definitionEn: 'Additional cost incurred as a result of choosing an alternative.' },
      { term: '增量收入', termEn: 'Incremental revenue', definition: '因選擇某方案而額外產生的收入。', definitionEn: 'Additional revenue earned as a result of choosing an alternative.' },
      { term: '可避免成本', termEn: 'Avoidable cost', definition: '若放棄某方案或部門即可節省的成本。', definitionEn: 'A cost that can be saved if an option or segment is discontinued.' },
      { term: '沉沒成本', termEn: 'Sunk cost', definition: '已經發生且不能因未來決策改變的成本。', definitionEn: 'A cost already incurred that cannot be changed by future decisions.' },
      { term: '承諾成本', termEn: 'Committed cost', definition: '企業已承諾或必須承擔的未來成本。', definitionEn: 'A future cost that the business has already committed to or must incur.' },
      { term: '不可避免成本', termEn: 'Unavoidable cost', definition: '不論採取哪個方案都不能避免的成本。', definitionEn: 'A cost that cannot be avoided under any alternative.' },
      { term: '特殊訂單', termEn: 'Special order', definition: '通常以特別價格提出、需獨立評估是否接受的訂單。', definitionEn: 'An order offered at a special price and assessed separately for acceptance.' },
      { term: '自製或外購', termEn: 'Make-or-buy decision', definition: '比較內部生產與向外部供應商購買的短期決策。', definitionEn: 'A short-term decision comparing internal production with purchasing from an external supplier.' },
      { term: '分離點', termEn: 'Split-off point', definition: '聯產品開始可單獨識別或出售的生產點。', definitionEn: 'The production point at which joint products become separately identifiable or saleable.' },
      { term: '進一步加工', termEn: 'Further processing', definition: '在產品可出售後繼續加工以取得更高售價的安排。', definitionEn: 'Continuing to process a saleable product to obtain a higher selling price.' },
      { term: '共同固定成本', termEn: 'Common fixed cost', definition: '由多個部門共同承擔、通常不會因取消單一部門而消失的固定成本。', definitionEn: 'A fixed cost shared by multiple segments and usually not eliminated by dropping one segment.' },
    ],
    examTips: [
      { zh: '決策題先畫兩欄比較方案，只放未來且會改變的項目。沉沒成本、共同固定成本和不可避免成本通常剔除。', en: 'For decision questions, compare alternatives in two columns and include only future items that change. Sunk costs, common fixed costs and unavoidable costs are usually excluded.' },
      { zh: '材料和人工的相關成本要看是否已有存貨、是否可替代使用、是否需重新購入，以及閒置人工是否會因決策而增加成本。', en: 'For materials and labour, consider whether inventory is already held, whether there is alternative use, whether replacement is needed and whether idle labour creates extra cost.' },
      { zh: '不要只給「接受」或「拒絕」。高分答案要列出增量收入、增量成本、淨影響，並補充產能、品質、顧客關係等非財務因素。', en: 'Do not only state “accept” or “reject”. High-scoring answers show incremental revenue, incremental costs, net effect and relevant non-financial factors such as capacity, quality and customer relationship.' },
    ],
    questions: [
      { question: '為何沉沒成本不應影響短期決策？', questionEn: 'Why should sunk costs not affect short-term decisions?', answer: '沉沒成本已經發生，不能因未來選擇而改變；決策應比較未來會因方案不同而改變的收入和成本。', answerEn: 'Sunk costs have already been incurred and cannot be changed by future choices; decisions should compare future revenues and costs that differ between alternatives.' },
      { question: '接受特殊訂單時，何時需要考慮機會成本？', questionEn: 'When should opportunity cost be considered in accepting a special order?', answer: '當沒有閒置產能，接受特殊訂單會犧牲正常銷售或其他用途時，放棄的貢獻就是機會成本。', answerEn: 'When there is no spare capacity and accepting the special order sacrifices normal sales or another use, the contribution forgone is an opportunity cost.' },
      { question: '進一步加工決策中，為何共同成本通常不相關？', questionEn: 'Why are joint costs usually irrelevant in a further-processing decision?', answer: '共同成本在分離點前已經發生，無論出售或進一步加工都不會改變；決策只看分離點後的額外收入和額外成本。', answerEn: 'Joint costs have been incurred before the split-off point and will not change whether the product is sold or processed further; the decision considers only additional revenue and additional cost after split-off.' },
      { question: '虧損部門是否一定應該取消？', questionEn: 'Should a loss-making segment always be eliminated?', answer: '不一定。若部門貢獻大於可避免固定成本，取消後企業會失去淨貢獻，整體利潤可能下降。', answerEn: 'Not necessarily. If the segment’s contribution exceeds avoidable fixed costs, dropping it removes net contribution and may reduce overall profit.' },
    ],
  },
]
