import { BAFSStrandId } from './curriculum'

export interface NoteChapter {
  title: string
  titleEn: string
  summary: string
}

export interface BAFSNotePart {
  id: string
  strand: BAFSStrandId
  sourceBook: string
  code: string
  title: string
  description: string
  chapters: NoteChapter[]
  keyPoints: string[]
  checklist: string[]
}

export const BAFS_NOTE_PARTS: BAFSNotePart[] = [
  {
    id: 'accounting-c1',
    strand: 'accounting',
    sourceBook: "Frank Wood's Accounting 1",
    code: 'C1',
    title: '香港商業環境',
    description: '理解企業在香港經濟中的角色、企業擁有權形式及社會責任。',
    chapters: [
      { title: '香港商業環境', titleEn: "Hong Kong's Business Environment", summary: '認識第一、第二及第三產業，以及企業對香港經濟的作用。' },
      { title: '企業擁有權形式', titleEn: 'Forms of Business Ownership', summary: '比較獨資、合夥及有限公司的特點、風險與責任。' },
      { title: '商業道德與社會責任', titleEn: 'Business Ethics and Social Responsibilities', summary: '分析企業決策如何影響持份者及社會。' },
    ],
    keyPoints: ['產業分類與企業角色', '企業擁有權、控制權及法律責任', '持份者、商業道德及社會責任'],
    checklist: ['能比較不同企業形式的優缺點', '能辨認商業決策涉及的持份者', '能用案例說明企業的社會責任'],
  },
  {
    id: 'accounting-c2',
    strand: 'accounting',
    sourceBook: "Frank Wood's Accounting 1",
    code: 'C2',
    title: '企業管理基礎',
    description: '掌握基本管理職能、企業功能及中小企的特點。',
    chapters: [
      { title: '管理職能', titleEn: 'Management Functions', summary: '理解規劃、組織、領導及控制如何協助企業達成目標。' },
      { title: '主要企業功能', titleEn: 'Key Business Functions', summary: '辨認市場、人力資源、營運及財務等功能的相互關係。' },
      { title: '中小型企業', titleEn: 'Small and Medium Enterprises', summary: '分析中小企的優勢、限制及對香港經濟的貢獻。' },
    ],
    keyPoints: ['四項管理職能', '企業功能之間的協作', '中小企的特點與挑戰'],
    checklist: ['能以情境辨認管理職能', '能解釋不同企業功能如何配合', '能分析中小企面對的限制'],
  },
  {
    id: 'accounting-c3',
    strand: 'accounting',
    sourceBook: "Frank Wood's Accounting 1",
    code: 'C3',
    title: '個人理財',
    description: '建立利息、信貸、個人理財及投資的基本概念。',
    chapters: [
      { title: '貨幣時間價值', titleEn: 'Time Value of Money', summary: '理解現值、終值及利息對資金價值的影響。' },
      { title: '消費者信貸', titleEn: 'Consumer Credit', summary: '比較不同借貸方式的成本、風險及還款責任。' },
      { title: '個人財務規劃與投資', titleEn: 'Personal Financial Planning and Investment', summary: '按目標、風險及回報制定理財計劃。' },
      { title: '股票投資', titleEn: 'Stock Trading as an Investment', summary: '認識股票交易、回報來源及主要風險。' },
    ],
    keyPoints: ['單利、複利、現值與終值', '信貸成本及還款能力', '風險與回報的取捨'],
    checklist: ['能計算基本利息及資金價值', '能比較信貸與投資方案', '能指出投資決定的主要風險'],
  },
  {
    id: 'accounting-a1',
    strand: 'accounting',
    sourceBook: "Frank Wood's Accounting 2",
    code: 'A1',
    title: '會計基礎',
    description: '由會計用途、會計等式及複式記帳建立完整基礎。',
    chapters: [
      { title: '會計的目的與角色', titleEn: 'Purposes and Role of Accounting', summary: '理解會計如何記錄、分類、總結及傳達財務資料。' },
      { title: '會計等式', titleEn: 'The Accounting Equation', summary: '運用資產、負債及資本的關係分析交易。' },
      { title: '複式記帳制度', titleEn: 'Double-Entry System', summary: '掌握每項交易的借方及貸方影響。' },
    ],
    keyPoints: ['會計資料使用者與決策需要', '資產 = 負債 + 資本', '借貸記帳規則'],
    checklist: ['能辨認交易影響的帳戶', '能保持會計等式平衡', '能正確記錄基本借貸分錄'],
  },
  {
    id: 'accounting-a2',
    strand: 'accounting',
    sourceBook: "Frank Wood's Accounting 2",
    code: 'A2',
    title: '原始分錄簿與分類帳',
    description: '學習由交易憑證到原始分錄簿及分類帳的記錄流程。',
    chapters: [
      { title: '原始分錄簿與分類帳（一）', titleEn: 'Books of Original Entry and Ledgers (I)', summary: '選擇合適的原始分錄簿記錄常見交易。' },
      { title: '原始分錄簿與分類帳（二）', titleEn: 'Books of Original Entry and Ledgers (II)', summary: '完成過帳、平帳及相關控制帳戶記錄。' },
    ],
    keyPoints: ['交易憑證與原始分錄簿', '分類帳過帳', '現金、銷售及採購交易記錄'],
    checklist: ['能選擇正確的原始分錄簿', '能把資料準確過帳至分類帳', '能完成帳戶結餘'],
  },
  {
    id: 'accounting-a3',
    strand: 'accounting',
    sourceBook: "Frank Wood's Accounting 2",
    code: 'A3',
    title: '試算表與獨資企業財務報表',
    description: '由試算表整理帳戶結餘，編製獨資企業財務報表。',
    chapters: [
      { title: '試算表', titleEn: 'Trial Balance', summary: '列出借貸結餘並檢查帳簿的算術準確性。' },
      { title: '獨資企業財務報表（一）', titleEn: 'Financial Statements for Sole Proprietorships (I)', summary: '計算銷貨成本及毛利，編製損益資料。' },
      { title: '獨資企業財務報表（二）', titleEn: 'Financial Statements for Sole Proprietorships (II)', summary: '編製完整損益表及財務狀況表。' },
    ],
    keyPoints: ['試算表用途與限制', '毛利與淨利計算', '損益表及財務狀況表格式'],
    checklist: ['能完成試算表', '能計算銷貨成本、毛利及淨利', '能編製基本財務報表'],
  },
  {
    id: 'accounting-a4',
    strand: 'accounting',
    sourceBook: "Frank Wood's Accounting 2",
    code: 'A4',
    title: '期末調整',
    description: '處理應計、預付、壞帳及呆帳準備對財務報表的影響。',
    chapters: [
      { title: '應計與預付', titleEn: 'Accruals and Prepayments', summary: '按權責發生概念把收入及支出歸入正確期間。' },
      { title: '壞帳與呆帳準備', titleEn: 'Bad Debts and Allowance for Doubtful Accounts', summary: '處理無法收回的應收帳款及估計信貸損失。' },
    ],
    keyPoints: ['權責發生概念', '調整分錄與報表影響', '壞帳及呆帳準備'],
    checklist: ['能分辨應計與預付項目', '能完成相關調整分錄', '能計算應收帳款淨額'],
  },
  {
    id: 'accounting-a5',
    strand: 'accounting',
    sourceBook: "Frank Wood's Accounting 2",
    code: 'A5',
    title: '非流動資產與存貨估值',
    description: '掌握折舊及存貨估值方法，理解其對利潤和資產的影響。',
    chapters: [
      { title: '非流動資產折舊', titleEn: 'Depreciation of Non-Current Assets', summary: '計算及記錄資產使用期間的折舊。' },
      { title: '存貨估值', titleEn: 'Valuation of Inventory', summary: '運用存貨估值原則計算期末存貨及銷貨成本。' },
    ],
    keyPoints: ['直線法及餘額遞減法', '折舊分錄與資產帳戶', '存貨估值及其報表影響'],
    checklist: ['能計算不同方法的折舊', '能完成折舊相關分錄', '能解釋存貨估值對利潤的影響'],
  },
  {
    id: 'accounting-a6',
    strand: 'accounting',
    sourceBook: "Frank Wood's Accounting 3",
    code: 'A6',
    title: '合夥企業會計',
    description: '處理合夥協議、商譽及資產重估等合夥企業會計事項。',
    chapters: [
      { title: '合夥企業財務報表', titleEn: 'Financial Statements for Partnerships', summary: '處理利潤分配、資本帳戶及往來帳戶。' },
      { title: '合夥商譽', titleEn: 'Partnership Goodwill', summary: '在合夥人變動時處理商譽調整。' },
      { title: '合夥資產重估', titleEn: 'Partnership Revaluation', summary: '記錄資產與負債重估及其對合夥人的影響。' },
    ],
    keyPoints: ['合夥協議與利潤分配', '固定及浮動資本帳戶', '商譽與重估調整'],
    checklist: ['能編製利潤分配帳', '能處理合夥人加入或退出', '能完成商譽及重估分錄'],
  },
  {
    id: 'accounting-a7',
    strand: 'accounting',
    sourceBook: "Frank Wood's Accounting 3",
    code: 'A7',
    title: '有限公司會計',
    description: '認識股份、債券及有限公司財務報表的主要格式。',
    chapters: [
      { title: '股份及債券發行', titleEn: 'Issue of Shares and Debentures', summary: '記錄公司籌集股本及借貸資本的交易。' },
      { title: '有限公司財務報表', titleEn: 'Financial Statements for Limited Companies', summary: '編製及理解有限公司主要財務報表。' },
    ],
    keyPoints: ['股本、股份及債券', '公司融資交易分錄', '有限公司財務報表'],
    checklist: ['能分辨股本與借貸資本', '能記錄股份及債券發行', '能編製公司財務報表'],
  },
  {
    id: 'accounting-a8',
    strand: 'accounting',
    sourceBook: "Frank Wood's Accounting 3",
    code: 'A8',
    title: '銀行調節與錯誤更正',
    description: '找出銀行差異及帳簿錯誤，完成更正與調節。',
    chapters: [
      { title: '銀行往來調節表', titleEn: 'Bank Reconciliation Statement', summary: '調節現金簿與銀行結單的差異。' },
      { title: '錯誤更正（一）', titleEn: 'Correction of Errors (I)', summary: '更正不影響試算表平衡的錯誤。' },
      { title: '錯誤更正（二）', titleEn: 'Correction of Errors (II)', summary: '運用暫記帳戶更正影響試算表平衡的錯誤。' },
    ],
    keyPoints: ['未達帳項與銀行調節', '錯誤類型及更正分錄', '暫記帳戶'],
    checklist: ['能更新現金簿並完成銀行調節', '能辨認錯誤是否影響試算表', '能完成更正分錄及暫記帳戶'],
  },
  {
    id: 'accounting-a9',
    strand: 'accounting',
    sourceBook: "Frank Wood's Accounting 4",
    code: 'A9',
    title: '財務分析',
    description: '運用會計比率評估企業的盈利能力、流動性及營運效率。',
    chapters: [
      { title: '財務分析', titleEn: 'Financial Analysis', summary: '計算、解釋及比較主要會計比率。' },
    ],
    keyPoints: ['盈利、流動性及效率比率', '比率變動原因', '比率分析的限制'],
    checklist: ['能正確計算主要比率', '能以數據支持分析結論', '能指出改善企業表現的方法'],
  },
  {
    id: 'accounting-a10',
    strand: 'accounting',
    sourceBook: "Frank Wood's Accounting 4",
    code: 'A10',
    title: '不完整記錄與會計原則',
    description: '由不完整資料重建帳目，並理解會計假設、原則及慣例。',
    chapters: [
      { title: '不完整記錄', titleEn: 'Incomplete Records', summary: '利用控制帳戶、資本比較及比率重建缺失資料。' },
      { title: '會計假設、原則及慣例', titleEn: 'Accounting Assumptions, Principles and Conventions', summary: '理解財務記錄與報告所依據的主要會計概念。' },
    ],
    keyPoints: ['資本比較與缺失數據推算', '控制帳戶與毛利率應用', '主要會計假設及原則'],
    checklist: ['能由不完整資料計算利潤', '能推算銷售、採購或現金數據', '能以會計原則解釋處理方法'],
  },
  {
    id: 'accounting-a11',
    strand: 'accounting',
    sourceBook: "Frank Wood's Accounting 4",
    code: 'A11',
    title: '成本分類與成本計算',
    description: '掌握成本術語，並比較吸收成本法與邊際成本法。',
    chapters: [
      { title: '成本分類、概念與術語', titleEn: 'Cost Classifications, Concepts and Terminology', summary: '分辨直接、間接、固定及變動成本。' },
      { title: '吸收成本法與邊際成本法', titleEn: 'Absorption Costing and Marginal Costing', summary: '比較兩種成本計算方法及其利潤差異。' },
    ],
    keyPoints: ['成本分類與成本單位', '製造費用分配', '吸收成本法與邊際成本法'],
    checklist: ['能正確分類成本', '能計算單位成本及存貨成本', '能解釋兩種方法的利潤差異'],
  },
  {
    id: 'accounting-a12',
    strand: 'accounting',
    sourceBook: "Frank Wood's Accounting 4",
    code: 'A12',
    title: '成本決策',
    description: '利用本量利分析及相關成本資料支援管理決策。',
    chapters: [
      { title: '本量利分析', titleEn: 'Cost-Volume-Profit Analysis', summary: '計算損益平衡點、安全邊際及目標利潤銷量。' },
      { title: '決策成本會計', titleEn: 'Cost Accounting for Decision-making', summary: '以相關成本分析短期管理決策。' },
    ],
    keyPoints: ['貢獻、損益平衡點及安全邊際', '相關成本與沉沒成本', '特殊訂單及自製或外購決策'],
    checklist: ['能完成本量利計算', '能辨認決策相關成本', '能以計算及非財務因素提出建議'],
  },
  {
    id: 'business-c1',
    strand: 'business',
    sourceBook: 'Business Management 1',
    code: 'C1',
    title: '香港商業環境',
    description: '理解企業擁有權、商業環境及企業責任。',
    chapters: [
      { title: '香港商業環境', titleEn: "Hong Kong's Business Environment", summary: '認識企業活動、產業分類及經濟角色。' },
      { title: '企業擁有權形式', titleEn: 'Forms of Business Ownership', summary: '比較主要企業形式的控制、責任與融資。' },
      { title: '商業道德與社會責任', titleEn: 'Business Ethics and Social Responsibilities', summary: '分析企業行為對持份者的影響。' },
    ],
    keyPoints: ['企業與香港經濟', '企業擁有權形式', '商業道德與社會責任'],
    checklist: ['能比較不同企業形式', '能辨認主要持份者', '能分析企業決策的社會影響'],
  },
  {
    id: 'business-c21',
    strand: 'business',
    sourceBook: 'Business Management 1',
    code: 'C2.1',
    title: '基礎會計概念',
    description: '理解會計用途、會計等式、複式記帳及試算表。',
    chapters: [
      { title: '會計的目的與角色', titleEn: 'Purposes and Role of Accounting', summary: '理解會計資料如何支援決策。' },
      { title: '會計等式', titleEn: 'The Accounting Equation', summary: '分析交易對資產、負債及資本的影響。' },
      { title: '複式記帳制度', titleEn: 'Double-Entry System', summary: '掌握基本借方與貸方記錄。' },
      { title: '試算表', titleEn: 'Trial Balance', summary: '整理帳戶結餘及檢查算術準確性。' },
    ],
    keyPoints: ['會計資料與決策', '會計等式', '複式記帳與試算表'],
    checklist: ['能分析交易影響', '能完成基本借貸分錄', '能編製試算表'],
  },
  {
    id: 'business-c22',
    strand: 'business',
    sourceBook: 'Business Management 1',
    code: 'C2.2',
    title: '財務報表與會計原則',
    description: '編製獨資企業財務報表，理解其背後的會計概念。',
    chapters: [
      { title: '獨資企業財務報表（一）', titleEn: 'Financial Statements for Sole Proprietorships (I)', summary: '計算銷貨成本、毛利及淨利。' },
      { title: '獨資企業財務報表（二）', titleEn: 'Financial Statements for Sole Proprietorships (II)', summary: '編製損益表及財務狀況表。' },
      { title: '會計假設、原則及慣例', titleEn: 'Accounting Assumptions, Principles and Conventions', summary: '理解常用會計處理的基本依據。' },
    ],
    keyPoints: ['財務報表格式', '利潤與財務狀況', '主要會計假設及原則'],
    checklist: ['能編製基本財務報表', '能分辨資本與收益項目', '能以會計原則解釋處理方法'],
  },
  {
    id: 'business-c3',
    strand: 'business',
    sourceBook: 'Business Management 1',
    code: 'C3',
    title: '個人理財',
    description: '掌握貨幣時間價值、信貸、財務規劃及投資。',
    chapters: [
      { title: '貨幣時間價值', titleEn: 'Time Value of Money', summary: '計算及比較不同時間點的資金價值。' },
      { title: '消費者信貸', titleEn: 'Consumer Credit', summary: '評估借貸成本及還款能力。' },
      { title: '個人財務規劃與投資', titleEn: 'Personal Financial Planning and Investment', summary: '按目標及風險選擇合適投資。' },
      { title: '股票投資', titleEn: 'Stock Trading as an Investment', summary: '理解股票交易的回報及風險。' },
    ],
    keyPoints: ['現值、終值及利息', '信貸成本', '投資風險與回報'],
    checklist: ['能完成基本資金價值計算', '能比較信貸產品', '能解釋投資組合的風險'],
  },
  {
    id: 'business-b1',
    strand: 'business',
    sourceBook: 'Business Management 2',
    code: 'B1',
    title: '管理與企業功能',
    description: '理解管理職能、企業功能及中小企的營運特點。',
    chapters: [
      { title: '管理職能', titleEn: 'Management Functions', summary: '分析規劃、組織、領導及控制。' },
      { title: '主要企業功能', titleEn: 'Key Business Functions', summary: '理解不同企業功能如何共同達成目標。' },
      { title: '中小型企業', titleEn: 'Small and Medium Enterprises', summary: '評估中小企的優勢、限制及發展需要。' },
    ],
    keyPoints: ['管理職能與管理層級', '企業功能協作', '中小企營運'],
    checklist: ['能以案例辨認管理職能', '能分析部門之間的衝突與協作', '能提出支援中小企的措施'],
  },
  {
    id: 'business-b2',
    strand: 'business',
    sourceBook: 'Business Management 2',
    code: 'B2',
    title: '人力規劃與招聘',
    description: '掌握人力規劃、招聘、甄選及績效評估。',
    chapters: [
      { title: '人力規劃與招聘', titleEn: 'Manpower Planning and Staffing', summary: '按企業需要規劃人力並選擇招聘方式。' },
      { title: '績效評估', titleEn: 'Performance Appraisal', summary: '利用評估制度改善表現及支援人事決策。' },
    ],
    keyPoints: ['人力供求與人力規劃', '招聘及甄選方法', '績效評估目的與方法'],
    checklist: ['能選擇合適招聘渠道', '能比較甄選方法', '能分析績效評估的優缺點'],
  },
  {
    id: 'business-b3',
    strand: 'business',
    sourceBook: 'Business Management 2',
    code: 'B3',
    title: '員工獎勵與發展',
    description: '理解獎勵、培訓及建立優質團隊的方法。',
    chapters: [
      { title: '獎勵管理', titleEn: 'Reward Management', summary: '運用金錢及非金錢獎勵提升員工動機。' },
      { title: '培訓與發展', titleEn: 'Training and Development', summary: '選擇合適培訓方法以提升能力。' },
      { title: '建立優質團隊', titleEn: 'Development of a Quality Workforce', summary: '透過溝通、領導及參與建立高效團隊。' },
    ],
    keyPoints: ['金錢與非金錢獎勵', '培訓方法', '員工動機及團隊質素'],
    checklist: ['能提出合適獎勵方案', '能比較在職與離職培訓', '能分析改善員工表現的方法'],
  },
  {
    id: 'business-b4',
    strand: 'business',
    sourceBook: 'Business Management 3',
    code: 'B4',
    title: '市場營銷與研究',
    description: '理解市場營銷角色及市場研究流程。',
    chapters: [
      { title: '市場營銷的角色', titleEn: 'Role of Marketing', summary: '理解市場營銷概念、顧客需要及企業目標。' },
      { title: '市場研究', titleEn: 'Marketing Research', summary: '收集及分析資料以支援市場決策。' },
    ],
    keyPoints: ['市場營銷概念', '市場研究步驟', '第一手及第二手資料'],
    checklist: ['能解釋市場營銷的重要性', '能選擇合適研究方法', '能指出研究方法的限制'],
  },
  {
    id: 'business-b5',
    strand: 'business',
    sourceBook: 'Business Management 3',
    code: 'B5',
    title: '消費者與市場定位',
    description: '分析消費者行為，並制定市場細分、目標及定位策略。',
    chapters: [
      { title: '消費者行為', titleEn: 'Consumer Behaviour', summary: '分析影響消費者購買決定的因素。' },
      { title: '市場細分、目標及定位', titleEn: 'Segmentation, Targeting and Positioning', summary: '選擇目標市場並建立清晰品牌定位。' },
    ],
    keyPoints: ['消費者決策因素', '市場細分準則', '目標市場與定位'],
    checklist: ['能分析消費者購買行為', '能提出有效市場細分', '能為產品建立定位'],
  },
  {
    id: 'business-b6',
    strand: 'business',
    sourceBook: 'Business Management 3',
    code: 'B6',
    title: '市場策略與顧客關係',
    description: '運用市場組合制定策略，並管理長期顧客關係。',
    chapters: [
      { title: '商品與服務市場策略（一）', titleEn: 'Marketing Strategies for Goods and Services (I)', summary: '制定產品及定價策略。' },
      { title: '商品與服務市場策略（二）', titleEn: 'Marketing Strategies for Goods and Services (II)', summary: '制定推廣及分銷策略。' },
      { title: '顧客關係管理', titleEn: 'Customer Relationship Management', summary: '利用服務與資料建立顧客忠誠。' },
    ],
    keyPoints: ['產品、價格、推廣及分銷', '服務市場策略', '顧客關係與忠誠'],
    checklist: ['能設計完整市場組合', '能按情境調整市場策略', '能提出改善顧客關係的方法'],
  },
  {
    id: 'business-b7',
    strand: 'business',
    sourceBook: 'Business Management 4',
    code: 'B7',
    title: '財務分析與預算',
    description: '運用會計比率及預算支援企業財務管理。',
    chapters: [
      { title: '財務分析', titleEn: 'Financial Analysis', summary: '利用會計比率評估企業表現。' },
      { title: '預算', titleEn: 'Budgeting', summary: '編製及運用預算作規劃和控制。' },
    ],
    keyPoints: ['盈利、流動性及效率比率', '預算編製', '預算控制及差異'],
    checklist: ['能計算及解釋主要比率', '能編製基本預算', '能分析實際與預算差異'],
  },
  {
    id: 'business-b8',
    strand: 'business',
    sourceBook: 'Business Management 4',
    code: 'B8',
    title: '融資與投資評估',
    description: '比較企業融資來源，並評估資本投資項目。',
    chapters: [
      { title: '融資來源', titleEn: 'Sources of Financing', summary: '按期限、成本及風險選擇融資方式。' },
      { title: '資本投資評估', titleEn: 'Capital Investment Appraisal', summary: '利用投資評估方法比較長期項目。' },
    ],
    keyPoints: ['內部及外部融資', '短期與長期融資', '投資回收與回報評估'],
    checklist: ['能比較融資來源', '能完成基本投資評估計算', '能考慮非財務因素作建議'],
  },
  {
    id: 'business-b9',
    strand: 'business',
    sourceBook: 'Business Management 4',
    code: 'B9',
    title: '營運資金與風險管理',
    description: '管理企業短期資金需要，並辨認及應對主要風險。',
    chapters: [
      { title: '營運資金管理', titleEn: 'Working Capital Management', summary: '平衡現金、存貨、應收及應付帳款。' },
      { title: '風險管理', titleEn: 'Risk Management', summary: '辨認企業風險並選擇控制及轉移方法。' },
    ],
    keyPoints: ['營運資金循環', '流動性與盈利能力取捨', '風險辨認與應對'],
    checklist: ['能分析營運資金問題', '能提出改善現金流的方法', '能為企業風險選擇應對措施'],
  },
]

export const getNotePart = (strand: BAFSStrandId, partId: string) =>
  BAFS_NOTE_PARTS.find((part) => part.strand === strand && part.id === partId)
