import { Exercise } from '../types';

export const ENERGY_USE_EXERCISES: Exercise[] = [
  {
    id: 'eu-001',
    type: 'multiple_choice',
    question:
      'In the figure, a light source is a perpendicular distance h above a horizontal surface. The amount of illuminance (unit: lux) of a point on the surface at a distance R from the source is directly proportional to',
    options: [
      'cos^2(theta) / R^2',
      'cos^2(theta) / h^2',
      'cos^3(theta) / h^2',
      'cos^2(theta) / R^2',
    ],
    answer: 'cos^3(theta) / h^2',
    explanation:
      'For a point source, illuminance at the surface is E = (Phi / 4piR^2) cos(theta). Since R = h / cos(theta), substituting gives E proportional to cos^3(theta) / h^2.',
    difficulty: 2,
    points: 15,
    hints: [
      'Start with the inverse-square law for a point source.',
      'Then include the cosine projection factor.',
      'Use R = h / cos(theta).',
    ],
    imagePaths: ['/physics/exercises/energy-and-use-of-energy/eu-001-question.png'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-002',
    type: 'multiple_choice',
    question: 'The Coefficient of Performance (COP) of a heat pump is',
    options: [
      'the ratio of energy absorbed from the cold reservoir to the energy rejected to the hot reservoir.',
      'the heat energy rejected to the hot reservoir per unit work done.',
      'the ratio between the total energy input to the useful work done.',
      'the ratio between the extra work input to the total energy input.',
    ],
    answer: 'the heat energy rejected to the hot reservoir per unit work done.',
    explanation:
      'For a heat pump, the useful output is the heat delivered to the hot reservoir. Therefore COP = Q_hot / W, the heat energy rejected to the hot reservoir per unit work done.',
    difficulty: 1,
    points: 10,
    hints: ['A heat pump is used for heating, not cooling.', 'The useful output is heat delivered to the hot side.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-003',
    type: 'multiple_choice',
    question:
      'A 100 W filament light bulb and a 22 W compact fluorescent lamp both produce a luminous flux of 1600 lm. Which of the following statements about the two light sources is/are correct?\n(1) Both light sources give out the same amount of energy in the form of electromagnetic waves in 1 s.\n(2) 78 J of electrical energy is converted to heat in the filament light bulb in 1 s.\n(3) Both light sources have the same brightness to the human eye when observed from the same distance.',
    options: [
      '(1) only',
      '(3) only',
      '(1) and (2) only',
      '(2) and (3) only',
    ],
    answer: '(3) only',
    explanation:
      'Equal luminous flux means the two sources give the same visible-light output, so they appear equally bright at the same distance. Statement (1) is false because total electromagnetic output, including infrared, need not be the same. Statement (2) is false because the filament bulb also emits visible light, so the heat loss is more than 78 J only if the useful light output is less than 22 J, not exactly 78 J from the given data.',
    difficulty: 2,
    points: 15,
    hints: [
      'Luminous flux compares visible light only.',
      'Brightness at the same distance follows the same luminous output.',
    ],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-004',
    type: 'multiple_choice',
    question:
      'A point light source with luminous flux F is illuminating a point P on a table surface as shown in the figure below. The illumination at point P is',
    options: [
      'F cos(theta) / (4pi r^2)',
      'F cos^2(theta) / (4pi r^2)',
      'F cos(90° - theta) / (4pi r^2)',
      'F cos^2(90° - theta) / (4pi r^2)',
    ],
    answer: 'F cos(theta) / (4pi r^2)',
    explanation:
      'Illuminance on a tilted receiving surface equals the inverse-square intensity multiplied by the cosine factor. Hence E = (F / 4pi r^2) cos(theta).',
    difficulty: 2,
    points: 15,
    hints: ['Use inverse-square law first.', 'Then multiply by the cosine projection factor.'],
    imagePaths: ['/physics/exercises/energy-and-use-of-energy/eu-004-question.png'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-005',
    type: 'multiple_choice',
    question:
      'Which of the following statements about an electric hotplate and an induction cooker is/are correct?\n(1) Both cookers make use of the heating effect of a current.\n(2) Only metal cooking pots can be used for both cookers.\n(3) In general, an induction cooker has a higher energy efficiency than an electric hotplate.',
    options: [
      '(1) only',
      '(2) only',
      '(1) and (3) only',
      '(2) and (3) only',
    ],
    answer: '(1) and (3) only',
    explanation:
      'An electric hotplate heats by resistive heating in the element, while an induction cooker heats by induced eddy currents in the cookware, so both rely on heating effects of current. Only induction cookers require suitable metal cookware. Induction cookers are generally more efficient because less energy is wasted heating the cooker itself.',
    difficulty: 2,
    points: 15,
    hints: [
      'Both devices ultimately rely on electrical currents causing heating.',
      'Only induction requires suitable metal cookware.',
    ],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-006',
    type: 'multiple_choice',
    question:
      'Which of the following lamps has the greatest end-use energy efficiency?\nA: luminous flux 750 lm, power rating 15 W\nB: luminous flux 900 lm, power rating 30 W\nC: luminous flux 750 lm, power rating 60 W\nD: luminous flux 600 lm, power rating 90 W',
    options: ['A', 'B', 'C', 'D'],
    answer: 'A',
    explanation:
      'Compare luminous efficacy in lm/W. A: 750/15 = 50 lm/W, B: 900/30 = 30 lm/W, C: 750/60 = 12.5 lm/W, D: 600/90 about 6.7 lm/W. The largest is A.',
    difficulty: 1,
    points: 10,
    hints: ['Compute luminous flux divided by power for each lamp.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-007',
    type: 'multiple_choice',
    question:
      'Below is a diagram of a room, the illuminance at corner P is E under the illumination of a point light source S as shown. Neglect the reflections from the room surfaces. The illuminance at point Q midway between P and S is',
    options: ['sqrt(2)E / cos(theta)', '2E cos(theta)', '4E', '8E'],
    answer: '4E',
    explanation:
      'Illuminance from a point source obeys the inverse-square law. Moving from P to Q halves the distance from the source, so the illuminance becomes 1 / (1/2)^2 = 4 times larger.',
    difficulty: 1,
    points: 10,
    hints: ['Use inverse-square dependence on distance only.'],
    imagePaths: ['/physics/exercises/energy-and-use-of-energy/eu-007-question.png'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-008',
    type: 'multiple_choice',
    question:
      'Estimate the time required to cool an insulated room of interior volume 29.0 m^3 from 37°C to 24°C by an air conditioner of cooling capacity 2.2 kW.\nGiven: density of air = 1.2 kg m^-3; specific heat capacity of air = 1000 J kg^-1 K^-1',
    options: ['171 s', '206 s', '380 s', '586 s'],
    answer: '206 s',
    explanation:
      'Mass of air = 1.2 x 29.0 = 34.8 kg. Heat removed = mcΔT = 34.8 x 1000 x (37 - 24) = 452400 J. Using E = Pt with P = 2.2 kW = 2200 W, the time is t = 452400 / 2200 about 206 s.',
    difficulty: 2,
    points: 15,
    hints: [
      'First find the mass of air from density and volume.',
      'Then use Q = mcΔT.',
      'Finally use E = Pt.',
    ],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-009',
    type: 'multiple_choice',
    question: 'Which of the following form of energy given out by a vacuum cleaner is useful ?\n(1) kinetic energy\n(2) sound energy\n(3) heat',
    options: ['(1) only', '(3) only', '(1) and (2) only', '(2) and (3) only'],
    answer: '(1) only',
    explanation:
      'The useful output of a vacuum cleaner is the kinetic effect of moving air that draws in dirt. Sound is unwanted noise and heat is wasted energy, so only kinetic energy is useful.',
    difficulty: 1,
    points: 10,
    hints: ['Identify the intended function of the device.', 'Useful output is the one that performs cleaning.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-010',
    type: 'multiple_choice',
    question: 'Which of the following form of energy may be given out by a TV set?\n(1) light energy\n(2) sound energy\n(3) heat energy',
    options: [
      '(1) and (2) only',
      '(1) and (3) only',
      '(2) and (3) only',
      '(1), (2) and (3)',
    ],
    answer: '(1), (2) and (3)',
    explanation:
      'A TV gives out light from the screen, sound from speakers, and heat as an unavoidable by-product of electrical operation. So all three forms may be given out.',
    difficulty: 1,
    points: 10,
    hints: ['Consider both useful outputs and unavoidable waste.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-011',
    type: 'multiple_choice',
    question: 'Which of the following concerning electrical appliances at home is/are correct ?\n(1) All electrical appliances would give out heat during operation.\n(2) All electrical appliances would give out sound during operation.\n(3) The heat given out by all electrical appliances is useless.',
    options: ['(1) only', '(3) only', '(1) and (2) only', '(2) and (3) only'],
    answer: '(1) only',
    explanation:
      'All electrical appliances produce some heat because current has a heating effect. Not all appliances produce sound, and heat is not always useless because heaters intentionally use heat as their useful output.',
    difficulty: 1,
    points: 10,
    hints: ['Current through a device always causes some heating.', 'A heater is the obvious counterexample for statement (3).'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-012',
    type: 'multiple_choice',
    question: 'The end-use energy efficiency of a lamp is 35%. If the power rating of the lamp is 60 W, how much useful energy is given out in 8 hours?',
    options: ['575 kJ', '605 kJ', '792 kJ', '848 kJ'],
    answer: '605 kJ',
    explanation:
      'Useful power output = 60 x 35% = 21 W. Useful energy in 8 hours is E = Pt = 21 x 8 x 3600 = 604800 J, about 605 kJ.',
    difficulty: 2,
    points: 15,
    hints: ['Convert efficiency into useful power first.', 'Then use E = Pt and convert to kJ.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-013',
    type: 'multiple_choice',
    question: 'Which of the following is/are the advantages of incandescent lamp, compared with the compact fluorescent lamp?\n(1) Incandescent lamp is cheaper.\n(2) Incandescent lamp has longer life.\n(3) Incandescent lamp has higher end-use energy efficiency.',
    options: ['(1) only', '(3) only', '(1) and (2) only', '(2) and (3) only'],
    answer: '(1) only',
    explanation:
      'Incandescent lamps are cheaper to buy. However, they have shorter life and lower end-use energy efficiency than CFLs, so only statement (1) is correct.',
    difficulty: 1,
    points: 10,
    hints: ['Compare purchase price, lifetime, and efficiency separately.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-014',
    type: 'multiple_choice',
    question: 'A filament lamp has a resistance of 960 ohms. An a.c. voltage of r.m.s. value 220 V is applied to it for 12 hours. If the end-use energy efficiency is 8%, how much heat is released to the surroundings during the time of operation ?',
    options: ['1.5 MJ', '2.0 MJ', '2.5 MJ', '3.0 MJ'],
    answer: '2.0 MJ',
    explanation:
      'Input power is P = V^2/R = 220^2 / 960 = 50.4 W. The fraction lost as heat is 92%, so heat power is 50.4 x 0.92 = 46.4 W. Over 12 hours, heat released is 46.4 x 12 x 3600 about 2.0 MJ.',
    difficulty: 2,
    points: 15,
    hints: ['First find electrical input power from V^2/R.', 'Only 8% is useful, so 92% becomes heat.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-015',
    type: 'multiple_choice',
    question: 'Which of the following concerning a CFL is NOT correct ?',
    options: [
      'The tube inside contains mercury.',
      'The phosphor coating converts ultra-violet radiation to visible light.',
      'During its operation, no heat is produced.',
      'Radiation is emitted by mercury atoms after they are excited.',
    ],
    answer: 'During its operation, no heat is produced.',
    explanation:
      'A CFL still produces some heat during operation. It does contain mercury, excited mercury atoms emit radiation, and the phosphor coating converts ultraviolet radiation into visible light.',
    difficulty: 1,
    points: 10,
    hints: ['Even efficient lamps are not perfectly efficient.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-016',
    type: 'multiple_choice',
    question: 'Which of the following is/are the disadvantages of CFL, compared with the conventional incandescent lamp ?\n(1) CFL is more expensive.\n(2) CFL has shorter life.\n(3) Improper disposal of CFL would cause the pollution of environment.',
    options: ['(1) and (2) only', '(1) and (3) only', '(2) and (3) only', '(1), (2) and (3)'],
    answer: '(1) and (3) only',
    explanation:
      'CFLs are more expensive and can pollute the environment if disposed of improperly because they contain mercury. They do not have shorter life; in general, their lifetime is longer than that of incandescent lamps.',
    difficulty: 1,
    points: 10,
    hints: ['Remember mercury content.', 'Compare lifespan with incandescent lamps.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-017',
    type: 'multiple_choice',
    question: 'Which of the following concerning a LED is/are correct ?\n(1) LED consists of two layers of semiconductor.\n(2) LED can be operated by d.c. or a.c. supply.\n(3) LED is usually installed in electronic circuit due to its small size.',
    options: ['(1) and (2) only', '(1) and (3) only', '(2) and (3) only', '(1), (2) and (3)'],
    answer: '(1) and (3) only',
    explanation:
      'An LED is a p-n junction, so it consists of two semiconductor regions. It is commonly used in electronic circuits because it is small. In basic operation, an LED is driven by d.c., not directly by a.c. as stated here.',
    difficulty: 1,
    points: 10,
    hints: ['Think of the LED as a p-n junction diode.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-018',
    type: 'multiple_choice',
    question: 'To which wavelength does the human eye respond most sensitively ?',
    options: ['500 nm', '550 nm', '600 nm', '650 nm'],
    answer: '550 nm',
    explanation:
      'The human eye is most sensitive in the green region, around 550 nm.',
    difficulty: 1,
    points: 10,
    hints: ['This is in the green part of the visible spectrum.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-019',
    type: 'multiple_choice',
    question: 'Which of the following affect the cost effectiveness of a lamp ?\n(1) price of the lamp\n(2) end-use energy efficiency of the lamp\n(3) size of the lamp',
    options: ['(1) and (2) only', '(1) and (3) only', '(2) and (3) only', '(1), (2) and (3)'],
    answer: '(1) and (2) only',
    explanation:
      'Cost effectiveness depends on how much the lamp costs and how efficiently it converts electrical energy into useful light. The physical size of the lamp is not a direct factor.',
    difficulty: 1,
    points: 10,
    hints: ['Think in terms of money spent and useful output obtained.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-020',
    type: 'multiple_choice',
    question: 'A CFL has a power rating of 18 W. It gives out light at a rate of 61 lm/W. What is the luminous flux that can be emitted by this CFL in normal working condition ?',
    options: ['1000 lm', '1100 lm', '1200 lm', '1300 lm'],
    answer: '1100 lm',
    explanation:
      'Luminous flux = luminous efficacy x power = 61 x 18 = 1098 lm, about 1100 lm.',
    difficulty: 1,
    points: 10,
    hints: ['Multiply lm/W by W.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-021',
    type: 'multiple_choice',
    question: 'Which of the following lamps can give out the greatest brightness in normal condition ?',
    options: [
      'a lamp of power rating 20 W with 62 lm/W',
      'a lamp of power rating 40 W with 36 lm/W',
      'a lamp of power rating 60 W with 25 lm/W',
      'a lamp of power rating 100 W with 12 lm/W',
    ],
    answer: 'a lamp of power rating 60 W with 25 lm/W',
    explanation:
      'Compare luminous flux = power x luminous efficacy. The four values are 1240 lm, 1440 lm, 1500 lm, and 1200 lm respectively. The greatest is 1500 lm, so the 60 W lamp with 25 lm/W is brightest.',
    difficulty: 1,
    points: 10,
    hints: ['Brightness here is determined by total luminous flux.', 'Compute lm for each option.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-022',
    type: 'multiple_choice',
    question: 'A small light bulb gives out light steadily in all directions. If the illuminance at a point 4 m from the lamp is 12 lx, what is the illuminance at a point 6 m from the lamp?',
    options: ['5.3 lx', '5.6 lx', '5.9 lx', '6.2 lx'],
    answer: '5.3 lx',
    explanation:
      'Use the inverse-square law: E is proportional to 1/r^2. So E2 = 12 x (4/6)^2 = 12 x 16/36 = 5.3 lx.',
    difficulty: 1,
    points: 10,
    hints: ['Illuminance from a point source follows inverse-square law.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-023',
    type: 'multiple_choice',
    question: 'The power rating of a lamp is 60 W. It emits light at 18 lm/W. If the lamp is installed at a height of 2.5 m above the desk, what is the illuminance at the desk?',
    options: ['10 lx', '12 lx', '14 lx', '16 lx'],
    answer: '14 lx',
    explanation:
      'Total luminous flux is 60 x 18 = 1080 lm. Assuming a point source radiating in all directions, illuminance directly below the lamp is E = Phi / (4pi r^2) = 1080 / (4pi x 2.5^2) about 14 lx.',
    difficulty: 2,
    points: 15,
    hints: ['First find total luminous flux.', 'Then apply E = Phi / 4pi r^2 for a point directly below.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-024',
    type: 'multiple_choice',
    question: 'The illuminance at a point 1.6 m from a lamp is 25 lx. If the lamp emits light at 45 lm/W, what is the power rating of the lamp?',
    options: ['12 W', '18 W', '24 W', '36 W'],
    answer: '18 W',
    explanation:
      'Luminous flux is Phi = E x 4pi r^2 = 25 x 4pi x 1.6^2 about 804 lm. Since luminous efficacy is 45 lm/W, power = 804 / 45 about 18 W.',
    difficulty: 2,
    points: 15,
    hints: ['Use illuminance to recover luminous flux first.', 'Then divide by lm/W.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-025',
    type: 'multiple_choice',
    question: 'A small light source emits visible light in all directions. Which of the following would NOT affect the illuminance on a certain surface ?',
    options: [
      'power of the light source',
      'orientation of the surface',
      'area of the surface',
      'distance of the surface from the light source',
    ],
    answer: 'area of the surface',
    explanation:
      'Illuminance depends on the luminous output of the source, the distance from the source, and the angle of the surface through the cosine factor. It does not directly depend on the total area of the receiving surface.',
    difficulty: 1,
    points: 10,
    hints: ['Think about what appears in the inverse-square law and Lambert cosine law.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-026',
    type: 'multiple_choice',
    question: 'The illuminance at a point in a room due to a small lamp can be found by the inverse-square law and Lambert’s cosine law. However, the actual illuminance is usually higher than the calculated value. Which of the following may be a factor to account for this deviation?\n(1) The lamp is not a point source.\n(2) There is reflection of light by the surrounding walls.\n(3) The light is not emitted evenly in all directions.',
    options: [
      '(1) and (2) only',
      '(1) and (3) only',
      '(2) and (3) only',
      '(1), (2) and (3)',
    ],
    answer: '(1), (2) and (3)',
    explanation:
      'The simple model assumes a point source with uniform emission and no reflections. Real lamps have finite size, room surfaces reflect light, and real lamps may not emit equally in all directions. All three can make the actual illuminance differ from the ideal estimate.',
    difficulty: 2,
    points: 15,
    hints: ['List the assumptions behind the simple illuminance formulas.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-027',
    type: 'multiple_choice',
    question: 'A small book is placed vertically below a lamp as shown in the figure. If the illuminance on the book is 26.5 lx, what is the luminous flux emitted by the lamp ?',
    options: ['679 lm', '725 lm', '846 lm', '984 lm'],
    answer: '984 lm',
    explanation:
      'Use E = (Phi / 4pi r^2) cos(theta). Substituting E = 26.5 lx, r = 1.6 m and theta = 30 degrees gives Phi about 984 lm.',
    difficulty: 2,
    points: 15,
    hints: ['Use both inverse-square law and cosine factor.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-028',
    type: 'multiple_choice',
    question: 'In the above figure, P is a point vertically below the lamp at the ceiling. If the luminous flux given out by the lamp is 1800 lm, what is the illuminance at the point Q ?',
    options: ['2.8 lx', '3.4 lx', '4.2 lx', '5.6 lx'],
    answer: '3.4 lx',
    explanation:
      'From the geometry, r = sqrt(3.2^2 + 4.0^2) = 5.12 m and theta = arctan(4.0 / 3.2) = 51.3 degrees. Then E = (Phi / 4pi r^2) cos(theta) = 1800 / (4pi x 5.12^2) x cos 51.3 degrees about 3.4 lx.',
    difficulty: 2,
    points: 15,
    hints: ['Find the actual source-to-point distance first.', 'Then include the cosine factor.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-029',
    type: 'multiple_choice',
    question: 'In the above figure, a small lamp giving out a total luminous flux of 1350 lm is installed at the middle of the ceiling. What is the illuminance at the point X ?',
    options: ['5.37 lx', '6.25 lx', '7.35 lx', '7.95 lx'],
    answer: '5.37 lx',
    explanation:
      'From the geometry, r = sqrt(4.0^2 + 1.6^2) = 4.31 m and theta = arctan(1.6 / 4.0) = 21.8 degrees. Then E = (Phi / 4pi r^2) cos(theta) = 1350 / (4pi x 4.31^2) x cos 21.8 degrees about 5.37 lx.',
    difficulty: 2,
    points: 15,
    hints: ['Use the distance from the lamp to X, not just the vertical height.', 'Then apply the cosine factor.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-030',
    type: 'multiple_choice',
    question:
      'The end-use energy efficiency of an induction cooker is 78%. If the cost of electricity is $0.95 per kWh, what is the expenditure to heat 1.5 kg of water from the room temperature of 25°C to boiling? Given that the specific heat capacity of water is 4200 J kg^-1 °C^-1.',
    options: ['$0.12', '$0.14', '$0.16', '$0.18'],
    answer: '$0.16',
    explanation:
      'Useful energy needed by the water is mcΔT = 1.5 x 4200 x (100 - 25) = 472500 J. Since the cooker is 78% efficient, electrical input energy is 472500 / 0.78 = 605769 J. Converting to kWh and multiplying by $0.95 per kWh gives a cost of about $0.16.',
    difficulty: 2,
    points: 15,
    hints: ['Find the useful heating energy first.', 'Then divide by efficiency to get input energy.', 'Convert joules to kWh before calculating cost.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-031',
    type: 'multiple_choice',
    question:
      'Which of the following concerning the operation of an induction cooker is/are correct ?\n(1) Magnetic field is produced by the high voltage of d.c. supply.\n(2) The change of magnetic field induces eddy current at the cover of the cooker.\n(3) Only cookware with ferrous metal can be used on an induction cooker.',
    options: ['(1) only', '(3) only', '(1) and (2) only', '(2) and (3) only'],
    answer: '(3) only',
    explanation:
      'An induction cooker operates with alternating current, not d.c., to produce a changing magnetic field. The cooker top is not the part intended to carry induced current. The induced eddy currents are generated in suitable ferrous cookware, so only statement (3) is correct.',
    difficulty: 2,
    points: 15,
    hints: ['Induction requires a changing magnetic field.', 'Think about where the eddy currents are intended to flow.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-032',
    type: 'multiple_choice',
    question:
      'Which of the following can account for the reason that a gas cooker is much lower efficient than an induction cooker ?\n(1) Large amount of heat is lost to the surroundings with a gas cooker.\n(2) The material of the induction cooker would not get hot during cooking.\n(3) All the electrical energy supplied to an induction cooker would convert to the internal energy of the food.',
    options: ['(1) only', '(3) only', '(1) and (2) only', '(2) and (3) only'],
    answer: '(1) and (2) only',
    explanation:
      'A gas cooker wastes much more heat to the surroundings. In an induction cooker, the cookware is heated directly, so the cooker itself does not become as hot. Statement (3) is false because there are still losses in practice.',
    difficulty: 2,
    points: 15,
    hints: ['Compare where the heating happens in each device.', 'No real cooker is 100% efficient.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-033',
    type: 'multiple_choice',
    question:
      'The end-use energy efficiency of a gas cooker is 42%. If the cost of gas is $0.25 per MJ, find the expenditure to heat 1.2 kg of water from the room temperature of 25°C to boiling. Given that the specific heat capacity of water is 4200 J kg^-1 °C^-1.',
    options: ['$0.225', '$0.250', '$0.275', '$0.300'],
    answer: '$0.225',
    explanation:
      'Useful energy needed is mcΔT = 1.2 x 4200 x (100 - 25) = 378000 J. Input energy is 378000 / 0.42 = 900000 J = 0.9 MJ. At $0.25 per MJ, the cost is 0.9 x 0.25 = $0.225.',
    difficulty: 2,
    points: 15,
    hints: ['Compute useful heating energy first.', 'Use efficiency to get the fuel input energy.', 'Convert to MJ for the cost calculation.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-034',
    type: 'multiple_choice',
    question:
      'Which of the following is NOT an advantage of an induction cooker for cooking food, compared with a gas cooker ?',
    options: [
      'An induction cooker does not produce naked flame that may catch fire.',
      'An induction cooker would not burn off the oxygen in the room.',
      'A cookware made of metal should be used for an induction cooker.',
      'The end-use energy efficiency of an induction cooker is high.',
    ],
    answer: 'A cookware made of metal should be used for an induction cooker.',
    explanation:
      'Requiring metal cookware is a limitation, not an advantage. The other statements are genuine advantages of induction cooking compared with gas cooking.',
    difficulty: 1,
    points: 10,
    hints: ['Identify the option that describes a restriction instead of a benefit.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-035',
    type: 'multiple_choice',
    question:
      'Which of the following correctly compare(s) the cooking by conventional ovens and by microwave ovens?\n(1) Conventional ovens cook food by infrared radiation but microwave ovens cook food by microwave radiation.\n(2) Conventional ovens can cook food with a crispy surface but microwave ovens cannot.\n(3) Conventional ovens cook food by transferring heat from surface to the interior but microwave ovens cook food by transferring heat from the interior to the surface.',
    options: ['(1) and (2) only', '(1) and (3) only', '(2) and (3) only', '(1), (2) and (3)'],
    answer: '(1) and (2) only',
    explanation:
      'Conventional ovens mainly heat from the outside by thermal radiation and hot air, while microwave ovens heat by microwaves acting within the food. Conventional ovens can produce a crispy surface more easily. Statement (3) is not a correct general description because microwave heating is more volumetric rather than simply from interior to surface.',
    difficulty: 2,
    points: 15,
    hints: ['Compare how the two appliances deposit energy into food.', 'Think about surface browning and crisping.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-036',
    type: 'multiple_choice',
    question:
      'Suppose 1.2 kg of water is heated from 20°C to 90°C by an electric hotplate of power rating 1600 W in 7.5 minutes. Specific heat capacity of water is 4200 J kg^-1 °C^-1. What is the end-use energy efficiency of the cooker ?',
    options: ['37%', '49%', '56%', '62%'],
    answer: '49%',
    explanation:
      'Useful energy to the water is mcΔT = 1.2 x 4200 x (90 - 20) = 352800 J. Input electrical energy is Pt = 1600 x (7.5 x 60) = 720000 J. Efficiency = 352800 / 720000 = 0.49 = 49%.',
    difficulty: 2,
    points: 15,
    hints: ['Use mcΔT for useful output energy.', 'Use Pt for electrical input energy.', 'Efficiency is output divided by input.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-037',
    type: 'multiple_choice',
    question: 'The Coefficient of Performance (COP) of a refrigerator is',
    options: [
      'the ratio of energy absorbed from the cold reservoir to the energy rejected to the hot reservoir.',
      'the ratio between the total energy input to the useful work done.',
      'the ratio between the extra work input to the total energy input.',
      'the heat energy absorbed from the cold reservoir per unit work done.',
    ],
    answer: 'the heat energy absorbed from the cold reservoir per unit work done.',
    explanation:
      'For a refrigerator, the useful effect is removing heat from the cold reservoir. Therefore COP = Q_cold / W, the heat absorbed from the cold reservoir per unit work done.',
    difficulty: 1,
    points: 10,
    hints: ['A refrigerator is judged by how much heat it removes from the cold space.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-038',
    type: 'multiple_choice',
    question:
      'A heat pump can extract a heat of 2500 J from a cold reservoir and deliver a heat of 3000 J to a hot reservoir in 1 minute. What is its coefficient of performance ?',
    options: ['4', '5', '6', '8'],
    answer: '6',
    explanation:
      'Work input is W = Q_hot - Q_cold = 3000 - 2500 = 500 J. For a heat pump, COP = Q_hot / W = 3000 / 500 = 6.',
    difficulty: 1,
    points: 10,
    hints: ['First use energy conservation to find the work input.', 'Then use the heat-pump COP definition.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-039',
    type: 'multiple_choice',
    question:
      'An air-conditioner of rating power of 1500 W is installed inside a room. If the coefficient of performance is 2.86, what is the cooling capacity of the air-conditioner ?',
    options: ['524 W', '1050 W', '2145 W', '4290 W'],
    answer: '4290 W',
    explanation:
      'For an air-conditioner operating as a refrigerator, cooling capacity is Q_cold = COP x W = 2.86 x 1500 = 4290 W.',
    difficulty: 1,
    points: 10,
    hints: ['Cooling capacity equals COP times input power.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-040',
    type: 'multiple_choice',
    question:
      'An air-conditioner of power 850 W is installed inside a room of size 5 m x 4 m x 2.8 m. Density of air is 1.2 kg m^-3 and the specific heat capacity of air is 1006 J kg^-1 °C^-1. If the time taken to cause the temperature of the room to drop from 32°C to 25°C is 4 minutes after switching on the air-conditioner, what is the coefficient of performance of the air-conditioner?',
    options: ['2.3', '2.6', '2.9', '3.2'],
    answer: '2.3',
    explanation:
      'Mass of air is 5 x 4 x 2.8 x 1.2 = 67.2 kg. Heat removed is Q_cold = mcΔT = 67.2 x 1006 x (32 - 25) about 4.73 x 10^5 J. Work input is W = Pt = 850 x (4 x 60) = 2.04 x 10^5 J. So COP = Q_cold / W about 2.3.',
    difficulty: 2,
    points: 15,
    hints: ['Find the air mass from room volume and density.', 'Use mcΔT for heat removed.', 'Use Pt for electrical work input.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-041',
    type: 'multiple_choice',
    question: 'Which of the following concerning an air-conditioning system is correct ?',
    options: [
      'Conservation of energy cannot be applied.',
      'The flow of heat is from high temperature region to low temperature region.',
      'The heat rejected to the hot reservoir must be greater than the heat absorbed from the cold reservoir.',
      'Work done on the system is equal to the heat absorbed from the cold reservoir.',
    ],
    answer: 'The heat rejected to the hot reservoir must be greater than the heat absorbed from the cold reservoir.',
    explanation:
      'For an air-conditioning system, energy conservation gives Q_hot = Q_cold + W. Since the work input W is positive, Q_hot must be greater than Q_cold.',
    difficulty: 1,
    points: 10,
    hints: ['Apply energy conservation to the refrigeration cycle.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-042',
    type: 'multiple_choice',
    question: 'Which of the following concerning the grading types of EELS is correct ?',
    options: [
      'The more efficient an electrical appliance, the more expensive is the appliance.',
      'The label does not include the data of the power rating of the electrical appliance.',
      'The Annual energy consumption assumes the continuous use of the electrical appliance in one year.',
      'All electrical appliances are under the scheme of EELS.',
    ],
    answer: 'The label does not include the data of the power rating of the electrical appliance.',
    explanation:
      'EELS labels are for energy-efficiency grading and commonly show comparative efficiency and annual energy use, but not the basic power rating itself. The other statements are not generally correct.',
    difficulty: 1,
    points: 10,
    hints: ['Think about what EELS is meant to communicate: efficiency, not all raw nameplate specs.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-043',
    type: 'multiple_choice',
    question:
      'The figure shows the energy label of a washing machine. If the average working time per wash is 1.8 hours, estimate the average electric power consumed by the machine.',
    options: ['450 W', '534 W', '962 W', '1731 W'],
    answer: '534 W',
    explanation:
      'From the label, annual energy consumption is 250 kWh and the machine is assumed to run 260 washes per year. Total operating time per year is 260 x 1.8 = 468 h. Using E = Pt, average power is P = 250 kWh / 468 h = 0.534 kW = 534 W.',
    difficulty: 2,
    points: 15,
    hints: ['Use annual energy divided by annual operating time.', 'Convert kW to W at the end.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-044',
    type: 'multiple_choice',
    question:
      'Which of the following would cause a waste of energy at home ?\n(1) Leave the home without switching off the lights.\n(2) Use incandescent light instead of CFL.\n(3) Set the indoor temperature to 20°C when using the air-conditioner.',
    options: ['(1) and (2) only', '(1) and (3) only', '(2) and (3) only', '(1), (2) and (3)'],
    answer: '(1), (2) and (3)',
    explanation:
      'Leaving lights on wastes electricity, incandescent lamps are less efficient than CFLs, and setting the air-conditioner too low increases unnecessary cooling demand. All three cause energy waste.',
    difficulty: 1,
    points: 10,
    hints: ['Each option describes avoidable extra energy use.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-045',
    type: 'multiple_choice',
    question:
      'Which of the following would save energy at home ?\n(1) Use fans instead of air-conditioners.\n(2) Do not use the washing machine until a full load of clothes has been accumulated.\n(3) Leave the entertainment equipment in standby mode.',
    options: ['(1) and (2) only', '(1) and (3) only', '(2) and (3) only', '(1), (2) and (3)'],
    answer: '(1) and (2) only',
    explanation:
      'Fans generally use much less power than air-conditioners, and running a washing machine only when there is a full load reduces the number of cycles. Standby mode still consumes power, so it does not save energy.',
    difficulty: 1,
    points: 10,
    hints: ['Standby mode still uses electricity.', 'Reducing operating time usually saves energy.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-046',
    type: 'multiple_choice',
    question:
      'Why should we save energy ?\n(1) To reduce the use of fossil fuels which have limited supply.\n(2) To reduce the release of carbon dioxide which is one of the greenhouse gases that cause global warming.\n(3) To protect the Earth and our environment.',
    options: ['(1) and (2) only', '(1) and (3) only', '(2) and (3) only', '(1), (2) and (3)'],
    answer: '(1), (2) and (3)',
    explanation:
      'Saving energy reduces fossil fuel consumption, cuts carbon dioxide emissions, and helps reduce environmental damage. All three statements are valid reasons.',
    difficulty: 1,
    points: 10,
    hints: ['This is about both resource conservation and environmental impact.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-047',
    type: 'multiple_choice',
    question:
      'Suppose a heat pump can deliver a heat energy of 8500 J to the hot reservoir by absorbing 6500 J of heat energy from the cold reservoir, what is its coefficient of performance?',
    options: ['1.31', '2.25', '3.25', '4.25'],
    answer: '4.25',
    explanation:
      'For a heat pump, COP = Q_hot / W. The work input is W = Q_hot - Q_cold = 8500 - 6500 = 2000 J. Therefore COP = 8500 / 2000 = 4.25.',
    difficulty: 1,
    points: 10,
    hints: ['Use energy conservation first to find the work input.', 'Then use the heat-pump COP definition.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-048',
    type: 'multiple_choice',
    question:
      'A 100 W filament light bulb and a 22 W compact fluorescent lamp can produce the same luminous flux in normal use. The price of a filament light bulb is $10 and its duration life is 6 months. The price of a compact fluorescent lamp is $32 and its duration life is 3 years. Calculate the money saved in 3 years if the filament light bulb is replaced by the compact fluorescent lamp, assuming the lamp is used continuously in 3 years without switching off, and the cost of electricity is $1 per kWh.',
    options: ['$2022', '$2050', '$2078', '$2628'],
    answer: '$2078',
    explanation:
      'Power saving is 100 - 22 = 78 W = 0.078 kW. Over 3 years of continuous use, time is 3 x 365 x 24 h, so electricity cost saved is 0.078 x 3 x 365 x 24 x $1 = $2050 approximately. Also, using filament bulbs for 3 years requires six bulbs costing $60, while one CFL costs $32, saving another $28. Total saving is about $2078.',
    difficulty: 2,
    points: 15,
    hints: ['Compute energy-cost saving first.', 'Then compare bulb purchase costs over 3 years.', 'Add both savings.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-049',
    type: 'multiple_choice',
    question:
      'A point light source gives out a steady luminous flux of 2400 lm in all directions. Calculate the illuminance at the point P as shown in the above figure.',
    options: ['4.55 lux', '6.33 lux', '7.28 lux', '16.2 lux'],
    answer: '4.55 lux',
    explanation:
      'From the geometry, the source-to-point distance is r = sqrt(2.5^2 + 4.0^2) = 4.717 m and theta = arctan(4.0 / 2.5) about 58 degrees. Using E = (Phi / 4pi r^2) cos(theta), E = 2400 / (4pi x 4.717^2) x cos 58 degrees = 4.55 lux.',
    difficulty: 2,
    points: 15,
    hints: ['Find the actual distance first.', 'Then include the cosine factor.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-050',
    type: 'multiple_choice',
    question: 'Which of the following statements concerning an induction cooker is correct ?',
    options: [
      'An induction cooker makes use of the heating effect of the eddy current to give out heat.',
      'No heat is lost to the surroundings by the induction cooker during cooking.',
      'During operation, eddy current is induced in the cooker to generate heat.',
      'It is dangerous to touch the surface of the cooker as eddy current may be induced in our body.',
    ],
    answer: 'An induction cooker makes use of the heating effect of the eddy current to give out heat.',
    explanation:
      'In an induction cooker, a changing magnetic field induces eddy currents in the cookware, and the heating effect of those currents heats the pot. Heat is still lost to the surroundings, the eddy currents are in the cookware rather than the cooker body, and the human body is not treated as the intended conducting load in this context.',
    difficulty: 2,
    points: 15,
    hints: ['The cookware is what is heated directly.', 'Induction heating is based on eddy currents.'],
    sectionId: 'energy-and-use-of-energy',
  },
  {
    id: 'eu-051',
    type: 'multiple_choice',
    question:
      'The above figure shows the energy label of an air-conditioner. Which of the following statements is/are correct ?\n(1) The average power rating of the air-conditioner is 900 W.\n(2) The amount of heat that can be removed from the room by the air-conditioner in 1 hour is 2.25 kWh.\n(3) The coefficient of performance of the air-conditioner is 2.5',
    options: ['(1) and (2) only', '(1) and (3) only', '(2) and (3) only', '(1), (2) and (3)'],
    answer: '(1), (2) and (3)',
    explanation:
      'From the label data, annual energy use is 1080 kWh over 1200 h, so average power is 1080 / 1200 = 0.9 kW = 900 W. If the cooling capacity is 2.25 kW, then in 1 hour the heat removed is 2.25 kWh. Over 1200 h, the total cooling delivered is 2.25 x 1200 = 2700 kWh, so COP = 2700 / 1080 = 2.5. Therefore all three statements are correct.',
    difficulty: 2,
    points: 15,
    hints: ['Use annual energy divided by annual operating hours for average input power.', 'Then compare cooling output to electrical input.'],
    sectionId: 'energy-and-use-of-energy',
  },
];
