import { PhysicsTopic } from '../types';

// HKDSE 物理八大主题
export const PHYSICS_TOPICS: Omit<PhysicsTopic, 'chapters' | 'progress'>[] = [
  {
    id: 'temperature-gas',
    name: 'Temperature and Gas',
    nameCN: '温度与气体',
    icon: '🌡️',
    color: 'physics-temp',
    gradient: 'physics-gradient-temp',
    description: '探索温度、热传递和气体定律的奥秘',
  },
  {
    id: 'force-motion',
    name: 'Force and Motion',
    nameCN: '力学与运动',
    icon: '🚀',
    color: 'physics-force',
    gradient: 'physics-gradient-force',
    description: '理解力与运动的关系，掌握牛顿定律',
  },
  {
    id: 'wave-motion',
    name: 'Wave Motion',
    nameCN: '波动',
    icon: '🌊',
    color: 'physics-wave',
    gradient: 'physics-gradient-wave',
    description: '学习波的特性、反射、折射与干涉',
  },
  {
    id: 'electricity-magnetism',
    name: 'Electricity and Magnetism',
    nameCN: '电与磁',
    icon: '⚡',
    color: 'physics-electricity',
    gradient: 'physics-gradient-electricity',
    description: '电路、电磁感应和电磁波的应用',
  },
  {
    id: 'radioactivity-nuclear',
    name: 'Radioactivity and Nuclear Energy',
    nameCN: '放射性与核能',
    icon: '☢️',
    color: 'physics-nuclear',
    gradient: 'physics-gradient-nuclear',
    description: '原子核结构、放射性衰变和核能',
  },
  {
    id: 'astronomy-space',
    name: 'Astronomy and Space Science',
    nameCN: '天文与太空科学',
    icon: '🌌',
    color: 'physics-space',
    gradient: 'physics-gradient-space',
    description: '宇宙的奥秘、恒星演化和太空探索',
  },
  {
    id: 'atomic-world',
    name: 'Atomic World',
    nameCN: '原子世界',
    icon: '⚛️',
    color: 'physics-atomic',
    gradient: 'physics-gradient-atomic',
    description: '原子结构、量子理论基础',
  },
  {
    id: 'energy-use',
    name: 'Energy and Use of Energy',
    nameCN: '能量及能量的使用',
    icon: '💡',
    color: 'physics-energy',
    gradient: 'physics-gradient-energy',
    description: '能量转换、效率和可持续发展',
  },
];

// 成就列表
export const ACHIEVEMENTS = [
  {
    id: 'first-lesson',
    title: 'First Step',
    titleCN: '初次探索',
    description: '完成第一道练习题',
    icon: '🎯',
    category: 'practice' as const,
    requirement: 1,
  },
  {
    id: 'chapter-clear',
    title: 'Chapter Clear',
    titleCN: '章节通关',
    description: '完成一个章节（全部做完且正确率≥90%）',
    icon: '✅',
    category: 'learning' as const,
    requirement: 1,
  },
  {
    id: 'rocket-launch',
    title: 'Rocket Launch',
    titleCN: '火箭升空',
    description: '完成章节且正确率达到95%',
    icon: '🚀',
    category: 'challenge' as const,
    requirement: 1,
  },
  {
    id: 'warm-up',
    title: 'Warm-up',
    titleCN: '十题入门',
    description: '完成10道练习题',
    icon: '✨',
    category: 'practice' as const,
    requirement: 10,
  },
  {
    id: 'problem-solver',
    title: 'Problem Solver',
    titleCN: '解题高手',
    description: '完成100道练习题',
    icon: '🏆',
    category: 'practice' as const,
    requirement: 100,
  },
  {
    id: 'accuracy-master',
    title: 'Accuracy Master',
    titleCN: '高正确率',
    description: '平均正确率达到85%',
    icon: '🎯',
    category: 'challenge' as const,
    requirement: 85,
  },
  {
    id: 'streak-3',
    title: 'Streak 3',
    titleCN: '三日连击',
    description: '连续学习3天',
    icon: '🔥',
    category: 'challenge' as const,
    requirement: 3,
  },
  {
    id: 'week-streak',
    title: 'Weekly Warrior',
    titleCN: '周学习达人',
    description: '连续学习7天',
    icon: '🔥',
    category: 'challenge' as const,
    requirement: 7,
  },
  {
    id: 'mistake-fighter',
    title: 'Comeback',
    titleCN: '错题不怕',
    description: '累计答错10题',
    icon: '🧩',
    category: 'practice' as const,
    requirement: 10,
  },
  {
    id: 'study-time-5h',
    title: 'Study Time',
    titleCN: '坚持学习',
    description: '累计学习300分钟',
    icon: '⏳',
    category: 'learning' as const,
    requirement: 300,
  },
  {
    id: 'perfect-chapter',
    title: 'Perfect Chapter',
    titleCN: '零错通关',
    description: '完成章节且零错题',
    icon: '🌟',
    category: 'challenge' as const,
    requirement: 1,
  },
  {
    id: 'rocket-master',
    title: 'Rocket Master',
    titleCN: '火箭大师',
    description: '火箭升空累计3次',
    icon: '🚀',
    category: 'challenge' as const,
    requirement: 3,
  },
  {
    id: 'triple-chapter',
    title: 'Triple Chapter',
    titleCN: '连过三章',
    description: '完成3个章节',
    icon: '🏅',
    category: 'learning' as const,
    requirement: 3,
  },
  {
    id: 'weekly-goal',
    title: 'Weekly Goal',
    titleCN: '周目标达成',
    description: '完成每周学习目标',
    icon: '🎯',
    category: 'learning' as const,
    requirement: 1,
  },
  {
    id: 'daily-30',
    title: 'Daily 30',
    titleCN: '每日30分钟',
    description: '单日学习满30分钟',
    icon: '⏰',
    category: 'learning' as const,
    requirement: 30,
  },
  {
    id: 'perfect-streak-3',
    title: 'Perfect Streak',
    titleCN: '完美三连',
    description: '连续答对3题',
    icon: '🔥',
    category: 'practice' as const,
    requirement: 3,
  },
  {
    id: 'comeback',
    title: 'Comeback',
    titleCN: '错题逆转',
    description: '曾答错的题后来答对',
    icon: '🔄',
    category: 'practice' as const,
    requirement: 1,
  },
  {
    id: 'all-difficulty',
    title: 'All Difficulty',
    titleCN: '全难度通关',
    description: '难度1~5各完成至少5题',
    icon: '🧭',
    category: 'challenge' as const,
    requirement: 5,
  },
  {
    id: 'patience-scholar',
    title: 'Patience Scholar',
    titleCN: '耐心研究',
    description: '单题思考超过3分钟并答对',
    icon: '🧪',
    category: 'challenge' as const,
    requirement: 1,
  },
  {
    id: 'daily-focus',
    title: 'Daily Focus',
    titleCN: '每日专注',
    description: '单日学习满60分钟',
    icon: '🧘',
    category: 'learning' as const,
    requirement: 60,
  },
  {
    id: 'night-owl',
    title: 'Night Owl',
    titleCN: '夜猫学霸',
    description: '夜间学习满30分钟',
    icon: '🌙',
    category: 'special' as const,
    requirement: 30,
  },
  {
    id: 'topic-explorer',
    title: 'Topic Explorer',
    titleCN: '学科探索者',
    description: '探索3个不同物理主题',
    icon: '🧭',
    category: 'learning' as const,
    requirement: 3,
  },
];

// 学习等级配置
export const LEVEL_CONFIG = {
  experiencePerLevel: 1000,
  maxLevel: 50,
  levelTitles: [
    { min: 1, max: 5, title: '物理新手', titleEN: 'Physics Novice' },
    { min: 6, max: 10, title: '物理学徒', titleEN: 'Physics Apprentice' },
    { min: 11, max: 20, title: '物理探索者', titleEN: 'Physics Explorer' },
    { min: 21, max: 30, title: '物理学者', titleEN: 'Physics Scholar' },
    { min: 31, max: 40, title: '物理专家', titleEN: 'Physics Expert' },
    { min: 41, max: 50, title: '物理大师', titleEN: 'Physics Master' },
  ],
};
