import { Formula } from '../types';

export const WAVE_MOTION_FORMULAS: Formula[] = [
  {
    id: 'wmf-1',
    name: 'Wave Equation',
    nameCN: '波动方程',
    expression: 'v = f lambda',
    variables: [
      { symbol: 'v', name: 'wave speed', unit: 'm s^-1', description: '波速' },
      { symbol: 'f', name: 'frequency', unit: 'Hz', description: '频率' },
      { symbol: 'lambda', name: 'wavelength', unit: 'm', description: '波长' },
    ],
    description: '适用于机械波、电磁波、声波和水波，是整套波动题最常用的基本关系。',
    example: 'If f = 500 Hz and lambda = 0.68 m, then v = 340 m s^-1.',
  },
  {
    id: 'wmf-2',
    name: 'Reflection Law',
    nameCN: '反射定律',
    expression: 'i = r',
    variables: [
      { symbol: 'i', name: 'angle of incidence', unit: 'deg', description: '入射角' },
      { symbol: 'r', name: 'angle of reflection', unit: 'deg', description: '反射角' },
    ],
    description: '光、声和水波遇到边界时都满足入射角等于反射角。',
    example: 'If i = 35 deg, the reflected angle is also 35 deg.',
  },
  {
    id: 'wmf-3',
    name: "Snell's Law",
    nameCN: '折射定律',
    expression: 'n1 sin theta1 = n2 sin theta2',
    variables: [
      { symbol: 'n1', name: 'refractive index of medium 1', unit: '-', description: '介质1折射率' },
      { symbol: 'n2', name: 'refractive index of medium 2', unit: '-', description: '介质2折射率' },
      { symbol: 'theta1', name: 'incident angle', unit: 'deg', description: '入射角' },
      { symbol: 'theta2', name: 'refracted angle', unit: 'deg', description: '折射角' },
    ],
    description: '适用于光的折射，也常用 sin theta 与波速的比例关系处理波前折射题。',
    example: 'A ray entering glass bends towards the normal because n2 > n1.',
  },
  {
    id: 'wmf-4',
    name: 'Refractive Index',
    nameCN: '折射率',
    expression: 'n = c / v = sin i / sin r',
    variables: [
      { symbol: 'n', name: 'refractive index', unit: '-', description: '折射率' },
      { symbol: 'c', name: 'speed of light in vacuum', unit: 'm s^-1', description: '真空光速' },
      { symbol: 'v', name: 'speed in medium', unit: 'm s^-1', description: '介质中光速' },
    ],
    description: '用于光在不同介质中的速度、折射角和材料性质的换算。',
    example: 'If light speed in a material is 1.5 x 10^8 m s^-1, then n = 2.',
  },
  {
    id: 'wmf-5',
    name: 'Critical Angle',
    nameCN: '临界角',
    expression: 'sin c = 1 / n',
    variables: [
      { symbol: 'c', name: 'critical angle', unit: 'deg', description: '临界角' },
      { symbol: 'n', name: 'refractive index of denser medium', unit: '-', description: '较密介质折射率' },
    ],
    description: '用于全反射题，前提是光从较密介质射向较疏介质。',
    example: 'If n = 1.50, then c = sin^-1(1/1.50).',
  },
  {
    id: 'wmf-6',
    name: 'Apparent Depth',
    nameCN: '视深关系',
    expression: 'n = real depth / apparent depth',
    variables: [
      { symbol: 'n', name: 'refractive index', unit: '-', description: '折射率' },
      { symbol: 'real depth', name: 'real depth', unit: 'm', description: '真实深度' },
      { symbol: 'apparent depth', name: 'apparent depth', unit: 'm', description: '视深' },
    ],
    description: '处理池底、鱼、硬币等看起来变浅的典型折射题。',
    example: 'If real depth is 1.2 m and apparent depth is 0.9 m, then n = 1.33.',
  },
  {
    id: 'wmf-7',
    name: 'Lens Formula',
    nameCN: '透镜公式',
    expression: '1 / f = 1 / u + 1 / v',
    variables: [
      { symbol: 'f', name: 'focal length', unit: 'm', description: '焦距' },
      { symbol: 'u', name: 'object distance', unit: 'm', description: '物距' },
      { symbol: 'v', name: 'image distance', unit: 'm', description: '像距' },
    ],
    description: '凸透镜和凹透镜题的核心公式，注意虚像常按负像距处理。',
    example: 'If u = 12 cm and v = 24 cm, then f = 8 cm.',
  },
  {
    id: 'wmf-8',
    name: 'Linear Magnification',
    nameCN: '放大率',
    expression: 'm = v / u = image height / object height',
    variables: [
      { symbol: 'm', name: 'magnification', unit: '-', description: '放大率' },
      { symbol: 'v', name: 'image distance', unit: 'm', description: '像距' },
      { symbol: 'u', name: 'object distance', unit: 'm', description: '物距' },
    ],
    description: '用于判断像放大、缩小、等大，以及结合透镜公式反推焦距。',
    example: 'If m = 2 and u = 15 cm, then v = 30 cm.',
  },
  {
    id: 'wmf-9',
    name: "Young's Double-Slit Fringe Spacing",
    nameCN: '双缝条纹间距',
    expression: 'Delta y = lambda D / a',
    variables: [
      { symbol: 'Delta y', name: 'fringe spacing', unit: 'm', description: '条纹间距' },
      { symbol: 'lambda', name: 'wavelength', unit: 'm', description: '波长' },
      { symbol: 'D', name: 'slit-to-screen distance', unit: 'm', description: '双缝到屏距离' },
      { symbol: 'a', name: 'slit separation', unit: 'm', description: '双缝间距' },
    ],
    description: '用于双缝干涉条纹疏密、改变量趋势和反算双缝间距。',
    example: 'Greater lambda or D gives wider fringes; greater a gives narrower fringes.',
  },
  {
    id: 'wmf-10',
    name: 'Diffraction Grating Equation',
    nameCN: '光栅方程',
    expression: 'd sin theta = n lambda',
    variables: [
      { symbol: 'd', name: 'grating spacing', unit: 'm', description: '光栅间距' },
      { symbol: 'theta', name: 'diffraction angle', unit: 'deg', description: '衍射角' },
      { symbol: 'n', name: 'order', unit: '-', description: '级数' },
      { symbol: 'lambda', name: 'wavelength', unit: 'm', description: '波长' },
    ],
    description: '用于判断不同颜色、不同级次的位置，以及最大可见级次。',
    example: 'Smaller d or larger lambda gives a larger first-order diffraction angle.',
  },
  {
    id: 'wmf-11',
    name: 'Interference Conditions',
    nameCN: '干涉条件',
    expression: 'constructive: Delta x = n lambda; destructive: Delta x = (n + 1/2) lambda',
    variables: [
      { symbol: 'Delta x', name: 'path difference', unit: 'm', description: '程差' },
      { symbol: 'n', name: 'integer', unit: '-', description: '整数 0, 1, 2...' },
    ],
    description: '适用于双源干涉、扬声器题、水波干涉题，也可结合同相和反相判断。',
    example: 'If Delta x = 2 lambda, constructive interference occurs for in-phase sources.',
  },
  {
    id: 'wmf-12',
    name: 'Phase Difference',
    nameCN: '相位差',
    expression: 'phase difference = 2 pi Delta x / lambda',
    variables: [
      { symbol: 'Delta x', name: 'path difference', unit: 'm', description: '程差' },
      { symbol: 'lambda', name: 'wavelength', unit: 'm', description: '波长' },
    ],
    description: '在题目给程差时，可用来判断同相、反相与干涉类型。',
    example: 'If Delta x = lambda / 2, the phase difference is pi.',
  },
  {
    id: 'wmf-13',
    name: 'Echo / Sonar Distance',
    nameCN: '回声测距',
    expression: 'd = v t / 2',
    variables: [
      { symbol: 'd', name: 'one-way distance', unit: 'm', description: '单程距离' },
      { symbol: 'v', name: 'wave speed', unit: 'm s^-1', description: '波速' },
      { symbol: 't', name: 'round-trip time', unit: 's', description: '往返时间' },
    ],
    description: '用于声呐、回声、超声波测距和测速题。',
    example: 'If an echo returns in 0.40 s and v = 1500 m s^-1, depth = 300 m.',
  },
  {
    id: 'wmf-14',
    name: 'Audible Range',
    nameCN: '可听频率范围',
    expression: '20 Hz to 20000 Hz',
    variables: [],
    description: '常用于判断可听声、超声和次声的范围。',
    example: 'Ultrasound has frequency greater than 20000 Hz.',
  },
  {
    id: 'wmf-15',
    name: 'Sound Intensity Level',
    nameCN: '声强级',
    expression: 'level in decibel (dB)',
    variables: [
      { symbol: 'dB', name: 'decibel', unit: 'dB', description: '声强级单位' },
    ],
    description: '用于比较安静环境、图书馆、交通噪声、演唱会等典型声强级。',
    example: 'A quiet library is about 30 dB; normal conversation is about 60 dB.',
  },
];
